# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\shotSculpt_UI.ui'
#
# Created: Thu Apr  3 17:58:47 2025
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_shot_sculpt_ui(object):
    def setupUi(self, shot_sculpt_ui):
        shot_sculpt_ui.setObjectName("shot_sculpt_ui")
        shot_sculpt_ui.resize(441, 444)
        self.centralwidget = QtWidgets.QWidget(shot_sculpt_ui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head_hly = QtWidgets.QHBoxLayout()
        self.head_hly.setObjectName("head_hly")
        self.refresh_hly = QtWidgets.QHBoxLayout()
        self.refresh_hly.setObjectName("refresh_hly")
        self.refresh_tree_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_tree_btn.setText("")
        self.refresh_tree_btn.setObjectName("refresh_tree_btn")
        self.refresh_hly.addWidget(self.refresh_tree_btn)
        self.layer_oc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.layer_oc_btn.setText("")
        self.layer_oc_btn.setObjectName("layer_oc_btn")
        self.refresh_hly.addWidget(self.layer_oc_btn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grab_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.grab_cb.setChecked(True)
        self.grab_cb.setObjectName("grab_cb")
        self.horizontalLayout_2.addWidget(self.grab_cb)
        self.shader_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.shader_cb.setChecked(True)
        self.shader_cb.setObjectName("shader_cb")
        self.horizontalLayout_2.addWidget(self.shader_cb)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.ccd_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccd_btn.sizePolicy().hasHeightForWidth())
        self.ccd_btn.setSizePolicy(sizePolicy)
        self.ccd_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.ccd_btn.setObjectName("ccd_btn")
        self.horizontalLayout_3.addWidget(self.ccd_btn)
        self.refresh_hly.addLayout(self.horizontalLayout_3)
        self.head_hly.addLayout(self.refresh_hly)
        self.verticalLayout.addLayout(self.head_hly)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.stree = QtWidgets.QTreeWidget(self.centralwidget)
        self.stree.setStyleSheet("QTreeWidget {\n"
"        background-color: rgb(60, 60, 60);\n"
"        font-size: 14px;  /* 设置字体大小为 14 像素 */\n"
"    }\n"
"\n"
"QTreeWidget::item {\n"
"        min-height: 25px;  /* 设置项目的最小高度为 30 像素 */\n"
"    }")
        self.stree.setHeaderHidden(False)
        self.stree.setObjectName("stree")
        self.stree.header().setVisible(True)
        self.verticalLayout.addWidget(self.stree)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.easyin_cmb = QtWidgets.QComboBox(self.centralwidget)
        self.easyin_cmb.setMinimumSize(QtCore.QSize(0, 30))
        self.easyin_cmb.setObjectName("easyin_cmb")
        self.easyin_cmb.addItem("")
        self.easyin_cmb.addItem("")
        self.easyin_cmb.addItem("")
        self.horizontalLayout.addWidget(self.easyin_cmb)
        self.easyin_sp = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.easyin_sp.sizePolicy().hasHeightForWidth())
        self.easyin_sp.setSizePolicy(sizePolicy)
        self.easyin_sp.setMinimumSize(QtCore.QSize(0, 30))
        self.easyin_sp.setMinimum(1)
        self.easyin_sp.setObjectName("easyin_sp")
        self.horizontalLayout.addWidget(self.easyin_sp)
        self.holdin_sp = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holdin_sp.sizePolicy().hasHeightForWidth())
        self.holdin_sp.setSizePolicy(sizePolicy)
        self.holdin_sp.setMinimumSize(QtCore.QSize(0, 30))
        self.holdin_sp.setObjectName("holdin_sp")
        self.horizontalLayout.addWidget(self.holdin_sp)
        self.holdout_sp = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holdout_sp.sizePolicy().hasHeightForWidth())
        self.holdout_sp.setSizePolicy(sizePolicy)
        self.holdout_sp.setMinimumSize(QtCore.QSize(0, 30))
        self.holdout_sp.setObjectName("holdout_sp")
        self.horizontalLayout.addWidget(self.holdout_sp)
        self.easyout_sp = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.easyout_sp.sizePolicy().hasHeightForWidth())
        self.easyout_sp.setSizePolicy(sizePolicy)
        self.easyout_sp.setMinimumSize(QtCore.QSize(0, 30))
        self.easyout_sp.setMinimum(1)
        self.easyout_sp.setObjectName("easyout_sp")
        self.horizontalLayout.addWidget(self.easyout_sp)
        self.easyout_cmb = QtWidgets.QComboBox(self.centralwidget)
        self.easyout_cmb.setMinimumSize(QtCore.QSize(0, 30))
        self.easyout_cmb.setObjectName("easyout_cmb")
        self.easyout_cmb.addItem("")
        self.easyout_cmb.addItem("")
        self.easyout_cmb.addItem("")
        self.horizontalLayout.addWidget(self.easyout_cmb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        shot_sculpt_ui.setCentralWidget(self.centralwidget)

        self.retranslateUi(shot_sculpt_ui)
        QtCore.QMetaObject.connectSlotsByName(shot_sculpt_ui)

    def retranslateUi(self, shot_sculpt_ui):
        shot_sculpt_ui.setWindowTitle(QtWidgets.QApplication.translate("shot_sculpt_ui", "Shot Sculpt", None, -1))
        self.grab_cb.setText(QtWidgets.QApplication.translate("shot_sculpt_ui", "Grab", None, -1))
        self.shader_cb.setText(QtWidgets.QApplication.translate("shot_sculpt_ui", "Shader", None, -1))
        self.ccd_btn.setText(QtWidgets.QApplication.translate("shot_sculpt_ui", "Create Character Node", None, -1))
        self.easyin_cmb.setItemText(0, QtWidgets.QApplication.translate("shot_sculpt_ui", "linear", None, -1))
        self.easyin_cmb.setItemText(1, QtWidgets.QApplication.translate("shot_sculpt_ui", "auto", None, -1))
        self.easyin_cmb.setItemText(2, QtWidgets.QApplication.translate("shot_sculpt_ui", "spline", None, -1))
        self.easyout_cmb.setItemText(0, QtWidgets.QApplication.translate("shot_sculpt_ui", "linear", None, -1))
        self.easyout_cmb.setItemText(1, QtWidgets.QApplication.translate("shot_sculpt_ui", "auto", None, -1))
        self.easyout_cmb.setItemText(2, QtWidgets.QApplication.translate("shot_sculpt_ui", "spline", None, -1))

