# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(633, 589)
        Form.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadDrv_btn = QtWidgets.QPushButton(self.tab_3)
        self.loadDrv_btn.setObjectName("loadDrv_btn")
        self.horizontalLayout_4.addWidget(self.loadDrv_btn)
        self.del_btn = QtWidgets.QPushButton(self.tab_3)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_4.addWidget(self.del_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.node_list = QtWidgets.QListWidget(self.tab_3)
        self.node_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.node_list.setObjectName("node_list")
        self.verticalLayout_14.addWidget(self.node_list)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        self.driven_list = QtWidgets.QListWidget(self.tab_3)
        self.driven_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.driven_list.setObjectName("driven_list")
        self.verticalLayout_16.addWidget(self.driven_list)
        self.horizontalLayout_6.addLayout(self.verticalLayout_16)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mirrorSel_btn = QtWidgets.QPushButton(self.tab_3)
        self.mirrorSel_btn.setObjectName("mirrorSel_btn")
        self.horizontalLayout_2.addWidget(self.mirrorSel_btn)
        self.mirrorAll_btn = QtWidgets.QPushButton(self.tab_3)
        self.mirrorAll_btn.setObjectName("mirrorAll_btn")
        self.horizontalLayout_2.addWidget(self.mirrorAll_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.path_le = QtWidgets.QLineEdit(self.tab_3)
        self.path_le.setReadOnly(True)
        self.path_le.setObjectName("path_le")
        self.horizontalLayout.addWidget(self.path_le)
        self.load_btn = QtWidgets.QPushButton(self.tab_3)
        self.load_btn.setObjectName("load_btn")
        self.horizontalLayout.addWidget(self.load_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Imp_btn = QtWidgets.QPushButton(self.tab_3)
        self.Imp_btn.setObjectName("Imp_btn")
        self.horizontalLayout_3.addWidget(self.Imp_btn)
        self.expSel_btn = QtWidgets.QPushButton(self.tab_3)
        self.expSel_btn.setObjectName("expSel_btn")
        self.horizontalLayout_3.addWidget(self.expSel_btn)
        self.expAll_btn = QtWidgets.QPushButton(self.tab_3)
        self.expAll_btn.setObjectName("expAll_btn")
        self.horizontalLayout_3.addWidget(self.expAll_btn)
        self.expScene_btn = QtWidgets.QPushButton(self.tab_3)
        self.expScene_btn.setObjectName("expScene_btn")
        self.horizontalLayout_3.addWidget(self.expScene_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loadDrv_btn.setText(_translate("Form", "Load Driver Nodes"))
        self.del_btn.setText(_translate("Form", "Delete Useless Nodes"))
        self.label_9.setText(_translate("Form", "Node"))
        self.label_11.setText(_translate("Form", "Driven"))
        self.mirrorSel_btn.setText(_translate("Form", "Mirror Selected Driven"))
        self.mirrorAll_btn.setText(_translate("Form", "Mirror All Driven"))
        self.label.setText(_translate("Form", "select file path"))
        self.load_btn.setText(_translate("Form", "Load"))
        self.Imp_btn.setText(_translate("Form", "Import"))
        self.expSel_btn.setText(_translate("Form", "Export Selected Driven"))
        self.expAll_btn.setText(_translate("Form", "Export All Driven"))
        self.expScene_btn.setText(_translate("Form", "Export Scene SDK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "SDK"))


