# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\controlToolsUI.ui'
#
# Created: Thu Apr 17 13:03:37 2025
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ctrl_win(object):
    def setupUi(self, ctrl_win):
        ctrl_win.setObjectName("ctrl_win")
        ctrl_win.resize(342, 759)
        ctrl_win.setMinimumSize(QtCore.QSize(342, 715))
        self.gridLayout = QtWidgets.QGridLayout(ctrl_win)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ctrl_win)
        self.frame.setMinimumSize(QtCore.QSize(0, 45))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("background-color:rgb(42,42,42);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(4, 2, 8, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.controlTools_label = QtWidgets.QLabel(self.frame)
        self.controlTools_label.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.controlTools_label.setFont(font)
        self.controlTools_label.setStyleSheet("color:lightGrey")
        self.controlTools_label.setIndent(10)
        self.controlTools_label.setObjectName("controlTools_label")
        self.horizontalLayout_3.addWidget(self.controlTools_label)
        self.controlTools_help = QtWidgets.QPushButton(self.frame)
        self.controlTools_help.setMaximumSize(QtCore.QSize(30, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rigBuild/icons/helpMeduim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlTools_help.setIcon(icon)
        self.controlTools_help.setFlat(True)
        self.controlTools_help.setObjectName("controlTools_help")
        self.horizontalLayout_3.addWidget(self.controlTools_help)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.create_gb = QtWidgets.QGroupBox(ctrl_win)
        self.create_gb.setMinimumSize(QtCore.QSize(0, 100))
        self.create_gb.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.create_gb.setFont(font)
        self.create_gb.setObjectName("create_gb")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.create_gb)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.snap_lb = QtWidgets.QLabel(self.create_gb)
        self.snap_lb.setMinimumSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.snap_lb.setFont(font)
        self.snap_lb.setObjectName("snap_lb")
        self.gridLayout_2.addWidget(self.snap_lb, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.snap_line = QtWidgets.QLineEdit(self.create_gb)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.snap_line.setFont(font)
        self.snap_line.setObjectName("snap_line")
        self.horizontalLayout_5.addWidget(self.snap_line)
        self.snap_btn = QtWidgets.QPushButton(self.create_gb)
        self.snap_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.snap_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.snap_btn.setFont(font)
        self.snap_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.snap_btn.setObjectName("snap_btn")
        self.horizontalLayout_5.addWidget(self.snap_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 2)
        self.name_lb = QtWidgets.QLabel(self.create_gb)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.name_lb.setFont(font)
        self.name_lb.setObjectName("name_lb")
        self.gridLayout_2.addWidget(self.name_lb, 0, 0, 1, 1)
        self.nameLine = QtWidgets.QLineEdit(self.create_gb)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.nameLine.setFont(font)
        self.nameLine.setText("")
        self.nameLine.setObjectName("nameLine")
        self.gridLayout_2.addWidget(self.nameLine, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.create_gb, 1, 0, 1, 1)
        self.shape_gb = QtWidgets.QGroupBox(ctrl_win)
        self.shape_gb.setMinimumSize(QtCore.QSize(292, 345))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.shape_gb.setFont(font)
        self.shape_gb.setFlat(False)
        self.shape_gb.setCheckable(False)
        self.shape_gb.setObjectName("shape_gb")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.shape_gb)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ctrl_listWidget = QtWidgets.QListWidget(self.shape_gb)
        self.ctrl_listWidget.setBaseSize(QtCore.QSize(272, 0))
        self.ctrl_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ctrl_listWidget.setIconSize(QtCore.QSize(70, 70))
        self.ctrl_listWidget.setMovement(QtWidgets.QListView.Static)
        self.ctrl_listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.ctrl_listWidget.setGridSize(QtCore.QSize(80, 80))
        self.ctrl_listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.ctrl_listWidget.setUniformItemSizes(False)
        self.ctrl_listWidget.setObjectName("ctrl_listWidget")
        self.gridLayout_6.addWidget(self.ctrl_listWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.shape_gb, 2, 0, 1, 1)
        self.modify_gb = QtWidgets.QGroupBox(ctrl_win)
        self.modify_gb.setMinimumSize(QtCore.QSize(0, 210))
        self.modify_gb.setMaximumSize(QtCore.QSize(16777215, 190))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.modify_gb.setFont(font)
        self.modify_gb.setObjectName("modify_gb")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.modify_gb)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.green_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.green_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.green_color_btn.setFont(font)
        self.green_color_btn.setObjectName("green_color_btn")
        self.horizontalLayout.addWidget(self.green_color_btn)
        self.violet_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.violet_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.violet_color_btn.setFont(font)
        self.violet_color_btn.setObjectName("violet_color_btn")
        self.horizontalLayout.addWidget(self.violet_color_btn)
        self.red_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.red_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.red_color_btn.setFont(font)
        self.red_color_btn.setObjectName("red_color_btn")
        self.horizontalLayout.addWidget(self.red_color_btn)
        self.yellow_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.yellow_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.yellow_color_btn.setFont(font)
        self.yellow_color_btn.setObjectName("yellow_color_btn")
        self.horizontalLayout.addWidget(self.yellow_color_btn)
        self.blue_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.blue_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.blue_color_btn.setFont(font)
        self.blue_color_btn.setObjectName("blue_color_btn")
        self.horizontalLayout.addWidget(self.blue_color_btn)
        self.cobalt_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 110, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 110, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.cobalt_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.cobalt_color_btn.setFont(font)
        self.cobalt_color_btn.setObjectName("cobalt_color_btn")
        self.horizontalLayout.addWidget(self.cobalt_color_btn)
        self.turquoise_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.turquoise_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.turquoise_color_btn.setFont(font)
        self.turquoise_color_btn.setObjectName("turquoise_color_btn")
        self.horizontalLayout.addWidget(self.turquoise_color_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.seprate_line_3 = QtWidgets.QFrame(self.modify_gb)
        self.seprate_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.seprate_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seprate_line_3.setObjectName("seprate_line_3")
        self.gridLayout_3.addWidget(self.seprate_line_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scale_add_btn = QtWidgets.QPushButton(self.modify_gb)
        self.scale_add_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.scale_add_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.scale_add_btn.setFont(font)
        self.scale_add_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scale_add_btn.setObjectName("scale_add_btn")
        self.horizontalLayout_2.addWidget(self.scale_add_btn)
        self.scale_reduce_btn = QtWidgets.QPushButton(self.modify_gb)
        self.scale_reduce_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.scale_reduce_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.scale_reduce_btn.setFont(font)
        self.scale_reduce_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scale_reduce_btn.setObjectName("scale_reduce_btn")
        self.horizontalLayout_2.addWidget(self.scale_reduce_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rox_btn = QtWidgets.QPushButton(self.modify_gb)
        self.rox_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.rox_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.rox_btn.setFont(font)
        self.rox_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.rox_btn.setObjectName("rox_btn")
        self.horizontalLayout_10.addWidget(self.rox_btn)
        self.roy_btn = QtWidgets.QPushButton(self.modify_gb)
        self.roy_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.roy_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.roy_btn.setFont(font)
        self.roy_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.roy_btn.setObjectName("roy_btn")
        self.horizontalLayout_10.addWidget(self.roy_btn)
        self.roz_btn = QtWidgets.QPushButton(self.modify_gb)
        self.roz_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.roz_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.roz_btn.setFont(font)
        self.roz_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.roz_btn.setObjectName("roz_btn")
        self.horizontalLayout_10.addWidget(self.roz_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.seprate_line = QtWidgets.QFrame(self.modify_gb)
        self.seprate_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.seprate_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seprate_line.setObjectName("seprate_line")
        self.gridLayout_3.addWidget(self.seprate_line, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mirrorControl_btn = QtWidgets.QPushButton(self.modify_gb)
        self.mirrorControl_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.mirrorControl_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.mirrorControl_btn.setFont(font)
        self.mirrorControl_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mirrorControl_btn.setObjectName("mirrorControl_btn")
        self.horizontalLayout_8.addWidget(self.mirrorControl_btn)
        self.mirrorShapel_btn = QtWidgets.QPushButton(self.modify_gb)
        self.mirrorShapel_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.mirrorShapel_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.mirrorShapel_btn.setFont(font)
        self.mirrorShapel_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mirrorShapel_btn.setObjectName("mirrorShapel_btn")
        self.horizontalLayout_8.addWidget(self.mirrorShapel_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.exportShape_btn = QtWidgets.QPushButton(self.modify_gb)
        self.exportShape_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.exportShape_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.exportShape_btn.setFont(font)
        self.exportShape_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.exportShape_btn.setObjectName("exportShape_btn")
        self.horizontalLayout_6.addWidget(self.exportShape_btn)
        self.importShape_btn = QtWidgets.QPushButton(self.modify_gb)
        self.importShape_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.importShape_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.importShape_btn.setFont(font)
        self.importShape_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.importShape_btn.setObjectName("importShape_btn")
        self.horizontalLayout_6.addWidget(self.importShape_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.modify_gb, 3, 0, 1, 1)

        self.retranslateUi(ctrl_win)
        QtCore.QMetaObject.connectSlotsByName(ctrl_win)

    def retranslateUi(self, ctrl_win):
        ctrl_win.setWindowTitle(QtWidgets.QApplication.translate("ctrl_win", "ControlTools", None, -1))
        self.controlTools_label.setText(QtWidgets.QApplication.translate("ctrl_win", "Control Tools", None, -1))
        self.create_gb.setTitle(QtWidgets.QApplication.translate("ctrl_win", "Name", None, -1))
        self.snap_lb.setText(QtWidgets.QApplication.translate("ctrl_win", "Snap To", None, -1))
        self.snap_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "   Get   ", None, -1))
        self.name_lb.setText(QtWidgets.QApplication.translate("ctrl_win", "Name", None, -1))
        self.shape_gb.setTitle(QtWidgets.QApplication.translate("ctrl_win", "Create", None, -1))
        self.modify_gb.setTitle(QtWidgets.QApplication.translate("ctrl_win", "Modify", None, -1))
        self.green_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "G", None, -1))
        self.violet_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "V", None, -1))
        self.red_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "R", None, -1))
        self.yellow_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Y", None, -1))
        self.blue_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "B", None, -1))
        self.cobalt_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "C", None, -1))
        self.turquoise_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "T", None, -1))
        self.scale_add_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Scale +", None, -1))
        self.scale_reduce_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Scale -", None, -1))
        self.rox_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Ro-X", None, -1))
        self.roy_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Ro-Y", None, -1))
        self.roz_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Ro-Z", None, -1))
        self.mirrorControl_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Mirror Control", None, -1))
        self.mirrorShapel_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Mirror Shape", None, -1))
        self.exportShape_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Export Shape", None, -1))
        self.importShape_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Import Shape", None, -1))

