# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainUI.ui'
#
# Created: Thu Apr 17 13:01:38 2025
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_rs_win(object):
    def setupUi(self, rs_win):
        rs_win.setObjectName("rs_win")
        rs_win.resize(380, 790)
        rs_win.setMinimumSize(QtCore.QSize(380, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(rs_win)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.assetInfoHBox = QtWidgets.QHBoxLayout()
        self.assetInfoHBox.setObjectName("assetInfoHBox")
        self.assetInfoFrame = QtWidgets.QFrame(rs_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetInfoFrame.sizePolicy().hasHeightForWidth())
        self.assetInfoFrame.setSizePolicy(sizePolicy)
        self.assetInfoFrame.setSizeIncrement(QtCore.QSize(0, 100))
        self.assetInfoFrame.setStyleSheet("background-color: rgb(60,60,60);\n"
"")
        self.assetInfoFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.assetInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.assetInfoFrame.setObjectName("assetInfoFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.assetInfoFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.assetsInfoHBox = QtWidgets.QHBoxLayout()
        self.assetsInfoHBox.setObjectName("assetsInfoHBox")
        self.idLb = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idLb.sizePolicy().hasHeightForWidth())
        self.idLb.setSizePolicy(sizePolicy)
        self.idLb.setMinimumSize(QtCore.QSize(120, 120))
        self.idLb.setText("")
        self.idLb.setObjectName("idLb")
        self.assetsInfoHBox.addWidget(self.idLb)
        self.assetsInfo01Line = QtWidgets.QFrame(self.assetInfoFrame)
        self.assetsInfo01Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.assetsInfo01Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.assetsInfo01Line.setObjectName("assetsInfo01Line")
        self.assetsInfoHBox.addWidget(self.assetsInfo01Line)
        self.assetsInfoVBox = QtWidgets.QVBoxLayout()
        self.assetsInfoVBox.setObjectName("assetsInfoVBox")
        self.assetsNameHBox = QtWidgets.QHBoxLayout()
        self.assetsNameHBox.setObjectName("assetsNameHBox")
        self.assetNameLabel = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetNameLabel.sizePolicy().hasHeightForWidth())
        self.assetNameLabel.setSizePolicy(sizePolicy)
        self.assetNameLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.assetNameLabel.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.assetNameLabel.setFont(font)
        self.assetNameLabel.setObjectName("assetNameLabel")
        self.assetsNameHBox.addWidget(self.assetNameLabel)
        self.assetNameDate = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetNameDate.sizePolicy().hasHeightForWidth())
        self.assetNameDate.setSizePolicy(sizePolicy)
        self.assetNameDate.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assetNameDate.setFont(font)
        self.assetNameDate.setText("")
        self.assetNameDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.assetNameDate.setObjectName("assetNameDate")
        self.assetsNameHBox.addWidget(self.assetNameDate)
        self.assetsInfoVBox.addLayout(self.assetsNameHBox)
        self.assetsDateHBox = QtWidgets.QHBoxLayout()
        self.assetsDateHBox.setObjectName("assetsDateHBox")
        self.createdLabel = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createdLabel.sizePolicy().hasHeightForWidth())
        self.createdLabel.setSizePolicy(sizePolicy)
        self.createdLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.createdLabel.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.createdLabel.setFont(font)
        self.createdLabel.setObjectName("createdLabel")
        self.assetsDateHBox.addWidget(self.createdLabel)
        self.createdDate = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createdDate.sizePolicy().hasHeightForWidth())
        self.createdDate.setSizePolicy(sizePolicy)
        self.createdDate.setMinimumSize(QtCore.QSize(0, 20))
        self.createdDate.setText("")
        self.createdDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.createdDate.setObjectName("createdDate")
        self.assetsDateHBox.addWidget(self.createdDate)
        self.assetsInfoVBox.addLayout(self.assetsDateHBox)
        self.assetsAuthorHBox = QtWidgets.QHBoxLayout()
        self.assetsAuthorHBox.setObjectName("assetsAuthorHBox")
        self.modLabel = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modLabel.sizePolicy().hasHeightForWidth())
        self.modLabel.setSizePolicy(sizePolicy)
        self.modLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.modLabel.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.modLabel.setFont(font)
        self.modLabel.setObjectName("modLabel")
        self.assetsAuthorHBox.addWidget(self.modLabel)
        self.modDate = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modDate.sizePolicy().hasHeightForWidth())
        self.modDate.setSizePolicy(sizePolicy)
        self.modDate.setMinimumSize(QtCore.QSize(0, 20))
        self.modDate.setText("")
        self.modDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.modDate.setObjectName("modDate")
        self.assetsAuthorHBox.addWidget(self.modDate)
        self.assetsInfoVBox.addLayout(self.assetsAuthorHBox)
        self.assetsInfo02Line = QtWidgets.QFrame(self.assetInfoFrame)
        self.assetsInfo02Line.setFrameShape(QtWidgets.QFrame.HLine)
        self.assetsInfo02Line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.assetsInfo02Line.setObjectName("assetsInfo02Line")
        self.assetsInfoVBox.addWidget(self.assetsInfo02Line)
        self.assetsEditHBox = QtWidgets.QHBoxLayout()
        self.assetsEditHBox.setObjectName("assetsEditHBox")
        self.setBtn = QtWidgets.QPushButton(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setBtn.sizePolicy().hasHeightForWidth())
        self.setBtn.setSizePolicy(sizePolicy)
        self.setBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.setBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setBtn.setFont(font)
        self.setBtn.setText("")
        self.setBtn.setCheckable(True)
        self.setBtn.setFlat(True)
        self.setBtn.setObjectName("setBtn")
        self.assetsEditHBox.addWidget(self.setBtn)
        self.rigTypeDate = QtWidgets.QLabel(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigTypeDate.sizePolicy().hasHeightForWidth())
        self.rigTypeDate.setSizePolicy(sizePolicy)
        self.rigTypeDate.setMinimumSize(QtCore.QSize(0, 20))
        self.rigTypeDate.setText("")
        self.rigTypeDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rigTypeDate.setObjectName("rigTypeDate")
        self.assetsEditHBox.addWidget(self.rigTypeDate)
        self.newRigBtn = QtWidgets.QPushButton(self.assetInfoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newRigBtn.sizePolicy().hasHeightForWidth())
        self.newRigBtn.setSizePolicy(sizePolicy)
        self.newRigBtn.setMinimumSize(QtCore.QSize(25, 25))
        self.newRigBtn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newRigBtn.setFont(font)
        self.newRigBtn.setText("")
        self.newRigBtn.setFlat(True)
        self.newRigBtn.setObjectName("newRigBtn")
        self.assetsEditHBox.addWidget(self.newRigBtn)
        self.assetsInfoVBox.addLayout(self.assetsEditHBox)
        self.assetsInfoHBox.addLayout(self.assetsInfoVBox)
        self.verticalLayout_4.addLayout(self.assetsInfoHBox)
        self.stratInfoLb = QtWidgets.QLabel(self.assetInfoFrame)
        self.stratInfoLb.setText("")
        self.stratInfoLb.setObjectName("stratInfoLb")
        self.verticalLayout_4.addWidget(self.stratInfoLb)
        self.assetInfoHBox.addWidget(self.assetInfoFrame)
        self.verticalLayout.addLayout(self.assetInfoHBox)
        self.envWdg = QtWidgets.QWidget(rs_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.envWdg.sizePolicy().hasHeightForWidth())
        self.envWdg.setSizePolicy(sizePolicy)
        self.envWdg.setObjectName("envWdg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.envWdg)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.assetFrame = QtWidgets.QFrame(self.envWdg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetFrame.sizePolicy().hasHeightForWidth())
        self.assetFrame.setSizePolicy(sizePolicy)
        self.assetFrame.setStyleSheet("")
        self.assetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.assetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.assetFrame.setObjectName("assetFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.assetFrame)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.assetList = QtWidgets.QListWidget(self.assetFrame)
        self.assetList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.assetList.setLineWidth(1)
        self.assetList.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.assetList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.assetList.setIconSize(QtCore.QSize(40, 40))
        self.assetList.setMovement(QtWidgets.QListView.Static)
        self.assetList.setFlow(QtWidgets.QListView.LeftToRight)
        self.assetList.setProperty("isWrapping", False)
        self.assetList.setResizeMode(QtWidgets.QListView.Fixed)
        self.assetList.setGridSize(QtCore.QSize(70, 70))
        self.assetList.setViewMode(QtWidgets.QListView.IconMode)
        self.assetList.setSelectionRectVisible(False)
        self.assetList.setObjectName("assetList")
        self.horizontalLayout_4.addWidget(self.assetList)
        self.verticalLayout_2.addWidget(self.assetFrame)
        self.searchHbl = QtWidgets.QHBoxLayout()
        self.searchHbl.setObjectName("searchHbl")
        self.seartch_lb = QtWidgets.QLabel(self.envWdg)
        self.seartch_lb.setObjectName("seartch_lb")
        self.searchHbl.addWidget(self.seartch_lb)
        self.searchLine = QtWidgets.QLineEdit(self.envWdg)
        self.searchLine.setText("")
        self.searchLine.setObjectName("searchLine")
        self.searchHbl.addWidget(self.searchLine)
        self.verticalLayout_2.addLayout(self.searchHbl)
        self.assetCmdHBox = QtWidgets.QHBoxLayout()
        self.assetCmdHBox.setObjectName("assetCmdHBox")
        self.newAssetBtn = QtWidgets.QPushButton(self.envWdg)
        self.newAssetBtn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.newAssetBtn.setFont(font)
        self.newAssetBtn.setStyleSheet("QPushButton{ \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:1 #116776, stop:0 #116776);\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color: #1d8ba3;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: #1d1d1d;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"background-color: #4b4b4b;\n"
"border-radius: 5px;\n"
"}")
        self.newAssetBtn.setFlat(False)
        self.newAssetBtn.setObjectName("newAssetBtn")
        self.assetCmdHBox.addWidget(self.newAssetBtn)
        self.verticalLayout_2.addLayout(self.assetCmdHBox)
        self.rootHBox = QtWidgets.QHBoxLayout()
        self.rootHBox.setSpacing(10)
        self.rootHBox.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.rootHBox.setContentsMargins(-1, -1, -1, 0)
        self.rootHBox.setObjectName("rootHBox")
        self.rootLine = QtWidgets.QLineEdit(self.envWdg)
        self.rootLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rootLine.setStyleSheet("QLineEdit{color:grey;\n"
"background-color:rgb(60,60,60);}\n"
"")
        self.rootLine.setFrame(False)
        self.rootLine.setReadOnly(True)
        self.rootLine.setObjectName("rootLine")
        self.rootHBox.addWidget(self.rootLine)
        self.rootBtn = QtWidgets.QPushButton(self.envWdg)
        self.rootBtn.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rootBtn.setFont(font)
        self.rootBtn.setStyleSheet("QPushButton{color:grey;\n"
"background-color:rgb(60,60,60);}\n"
"")
        self.rootBtn.setIconSize(QtCore.QSize(0, 0))
        self.rootBtn.setFlat(True)
        self.rootBtn.setObjectName("rootBtn")
        self.rootHBox.addWidget(self.rootBtn)
        self.rootHBox.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.rootHBox)
        self.verticalLayout.addWidget(self.envWdg)
        self.tabsWdg = QtWidgets.QTabWidget(rs_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabsWdg.sizePolicy().hasHeightForWidth())
        self.tabsWdg.setSizePolicy(sizePolicy)
        self.tabsWdg.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabsWdg.setUsesScrollButtons(True)
        self.tabsWdg.setTabsClosable(False)
        self.tabsWdg.setMovable(False)
        self.tabsWdg.setObjectName("tabsWdg")
        self.verticalLayout.addWidget(self.tabsWdg)
        self.assetPathHBox = QtWidgets.QHBoxLayout()
        self.assetPathHBox.setSpacing(10)
        self.assetPathHBox.setObjectName("assetPathHBox")
        self.assetPathLine = QtWidgets.QLineEdit(rs_win)
        self.assetPathLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.assetPathLine.setStyleSheet("QLineEdit{color:grey;\n"
"background-color:rgb(60,60,60);}\n"
"")
        self.assetPathLine.setFrame(False)
        self.assetPathLine.setReadOnly(True)
        self.assetPathLine.setObjectName("assetPathLine")
        self.assetPathHBox.addWidget(self.assetPathLine)
        self.openPathBtn = QtWidgets.QPushButton(rs_win)
        self.openPathBtn.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.openPathBtn.setFont(font)
        self.openPathBtn.setStyleSheet("QPushButton{color:grey;\n"
"background-color:rgb(60,60,60);}\n"
"")
        self.openPathBtn.setText("")
        self.openPathBtn.setIconSize(QtCore.QSize(30, 30))
        self.openPathBtn.setFlat(True)
        self.openPathBtn.setObjectName("openPathBtn")
        self.assetPathHBox.addWidget(self.openPathBtn)
        self.assetPathHBox.setStretch(0, 1)
        self.verticalLayout.addLayout(self.assetPathHBox)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(rs_win)
        self.tabsWdg.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(rs_win)

    def retranslateUi(self, rs_win):
        rs_win.setWindowTitle(QtWidgets.QApplication.translate("rs_win", "Rig Build", None, -1))
        self.assetNameLabel.setText(QtWidgets.QApplication.translate("rs_win", "NAME:", None, -1))
        self.createdLabel.setText(QtWidgets.QApplication.translate("rs_win", "DATE:", None, -1))
        self.modLabel.setText(QtWidgets.QApplication.translate("rs_win", "AUTHOR:", None, -1))
        self.seartch_lb.setText(QtWidgets.QApplication.translate("rs_win", "Search", None, -1))
        self.newAssetBtn.setText(QtWidgets.QApplication.translate("rs_win", "+ A S S E T +", None, -1))
        self.rootBtn.setText(QtWidgets.QApplication.translate("rs_win", ">>", None, -1))

