# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tagTools.ui'
#
# Created: Fri Apr 18 17:04:28 2025
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_tagToolsUI(object):
    def setupUi(self, tagToolsUI):
        tagToolsUI.setObjectName("tagToolsUI")
        tagToolsUI.resize(500, 866)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(tagToolsUI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pathHBox = QtWidgets.QHBoxLayout()
        self.pathHBox.setSpacing(6)
        self.pathHBox.setObjectName("pathHBox")
        self.pathLabel = QtWidgets.QLabel(tagToolsUI)
        self.pathLabel.setObjectName("pathLabel")
        self.pathHBox.addWidget(self.pathLabel)
        self.pathLine = QtWidgets.QLineEdit(tagToolsUI)
        self.pathLine.setStyleSheet("background-color:#555555\n"
"\n"
"")
        self.pathLine.setFrame(False)
        self.pathLine.setReadOnly(True)
        self.pathLine.setObjectName("pathLine")
        self.pathHBox.addWidget(self.pathLine)
        self.browseBtn = QtWidgets.QPushButton(tagToolsUI)
        self.browseBtn.setMaximumSize(QtCore.QSize(30, 24))
        self.browseBtn.setStyleSheet("background-color:gray")
        self.browseBtn.setAutoDefault(True)
        self.browseBtn.setDefault(False)
        self.browseBtn.setFlat(False)
        self.browseBtn.setObjectName("browseBtn")
        self.pathHBox.addWidget(self.browseBtn)
        self.reloadBtn = QtWidgets.QPushButton(tagToolsUI)
        self.reloadBtn.setMaximumSize(QtCore.QSize(30, 24))
        self.reloadBtn.setStyleSheet("background-color:gray")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/reloadSmall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadBtn.setIcon(icon)
        self.reloadBtn.setAutoDefault(True)
        self.reloadBtn.setDefault(False)
        self.reloadBtn.setFlat(False)
        self.reloadBtn.setObjectName("reloadBtn")
        self.pathHBox.addWidget(self.reloadBtn)
        self.verticalLayout_4.addLayout(self.pathHBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.tagKeyBtn = QtWidgets.QPushButton(tagToolsUI)
        self.tagKeyBtn.setMinimumSize(QtCore.QSize(100, 0))
        self.tagKeyBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tagKeyBtn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tagKeyBtn.setStyleSheet("QPushButton {background-color:#5B5B5B;}\n"
"QPushButton:disabled {background-color:grey; color:rgb(246, 246, 246);}\n"
"")
        self.tagKeyBtn.setCheckable(True)
        self.tagKeyBtn.setChecked(True)
        self.tagKeyBtn.setObjectName("tagKeyBtn")
        self.horizontalLayout_5.addWidget(self.tagKeyBtn)
        self.tagSpaceBtn = QtWidgets.QPushButton(tagToolsUI)
        self.tagSpaceBtn.setMinimumSize(QtCore.QSize(100, 0))
        self.tagSpaceBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tagSpaceBtn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tagSpaceBtn.setStyleSheet("QPushButton {background-color:#5B5B5B;}\n"
"QPushButton:disabled {background-color:grey; color:rgb(246, 246, 246);}\n"
"")
        self.tagSpaceBtn.setCheckable(True)
        self.tagSpaceBtn.setObjectName("tagSpaceBtn")
        self.horizontalLayout_5.addWidget(self.tagSpaceBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.widget_2 = QtWidgets.QWidget(tagToolsUI)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.splitter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.frame_4 = QtWidgets.QFrame(self.splitter)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ctrlList_6 = QtWidgets.QListWidget(self.frame_4)
        self.ctrlList_6.setMinimumSize(QtCore.QSize(0, 0))
        self.ctrlList_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ctrlList_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrlList_6.setStyleSheet("background-color:rgb(42,42,42)\n"
"")
        self.ctrlList_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ctrlList_6.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ctrlList_6.setUniformItemSizes(True)
        self.ctrlList_6.setObjectName("ctrlList_6")
        self.verticalLayout_6.addWidget(self.ctrlList_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(4, 4, 2, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addCtrlBtn_4 = QtWidgets.QPushButton(self.frame_4)
        self.addCtrlBtn_4.setMinimumSize(QtCore.QSize(0, 0))
        self.addCtrlBtn_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.addCtrlBtn_4.setFont(font)
        self.addCtrlBtn_4.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.addCtrlBtn_4.setObjectName("addCtrlBtn_4")
        self.horizontalLayout_3.addWidget(self.addCtrlBtn_4)
        self.rmCtrlBtn_4 = QtWidgets.QPushButton(self.frame_4)
        self.rmCtrlBtn_4.setMinimumSize(QtCore.QSize(0, 0))
        self.rmCtrlBtn_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rmCtrlBtn_4.setFont(font)
        self.rmCtrlBtn_4.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.rmCtrlBtn_4.setObjectName("rmCtrlBtn_4")
        self.horizontalLayout_3.addWidget(self.rmCtrlBtn_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.frame_5 = QtWidgets.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.frame_5)
        self.listWidget.setMinimumSize(QtCore.QSize(50, 0))
        self.listWidget.setStyleSheet("background-color:rgb(42,42,42)\n"
"")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setContentsMargins(2, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CBBtn_2 = QtWidgets.QPushButton(self.frame_5)
        self.CBBtn_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CBBtn_2.setFont(font)
        self.CBBtn_2.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.CBBtn_2.setObjectName("CBBtn_2")
        self.horizontalLayout_4.addWidget(self.CBBtn_2)
        self.saveBtn_5 = QtWidgets.QPushButton(self.frame_5)
        self.saveBtn_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.saveBtn_5.setFont(font)
        self.saveBtn_5.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.saveBtn_5.setObjectName("saveBtn_5")
        self.horizontalLayout_4.addWidget(self.saveBtn_5)
        self.saveBtn_4 = QtWidgets.QPushButton(self.frame_5)
        self.saveBtn_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.saveBtn_4.setFont(font)
        self.saveBtn_4.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.saveBtn_4.setObjectName("saveBtn_4")
        self.horizontalLayout_4.addWidget(self.saveBtn_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.splitter)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(tagToolsUI)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_2.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.splitter_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(1)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_2 = QtWidgets.QFrame(self.splitter_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ctrlList_5 = QtWidgets.QListWidget(self.frame_2)
        self.ctrlList_5.setMinimumSize(QtCore.QSize(0, 0))
        self.ctrlList_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ctrlList_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ctrlList_5.setStyleSheet("background-color:rgb(42,42,42)\n"
"")
        self.ctrlList_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ctrlList_5.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ctrlList_5.setUniformItemSizes(True)
        self.ctrlList_5.setObjectName("ctrlList_5")
        self.gridLayout.addWidget(self.ctrlList_5, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setContentsMargins(4, 4, 2, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addCtrlBtn_3 = QtWidgets.QPushButton(self.frame_2)
        self.addCtrlBtn_3.setMinimumSize(QtCore.QSize(0, 0))
        self.addCtrlBtn_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.addCtrlBtn_3.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.addCtrlBtn_3.setObjectName("addCtrlBtn_3")
        self.horizontalLayout_2.addWidget(self.addCtrlBtn_3)
        self.rmCtrlBtn_3 = QtWidgets.QPushButton(self.frame_2)
        self.rmCtrlBtn_3.setMinimumSize(QtCore.QSize(0, 0))
        self.rmCtrlBtn_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.rmCtrlBtn_3.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.rmCtrlBtn_3.setObjectName("rmCtrlBtn_3")
        self.horizontalLayout_2.addWidget(self.rmCtrlBtn_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.splitter_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(180, 180, 180)")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.conBtn = QtWidgets.QPushButton(self.frame_3)
        self.conBtn.setMinimumSize(QtCore.QSize(75, 0))
        self.conBtn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.conBtn.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.conBtn.setObjectName("conBtn")
        self.gridLayout_4.addWidget(self.conBtn, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(180, 180, 180)")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.conLine = QtWidgets.QLineEdit(self.frame_3)
        self.conLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.conLine.setStyleSheet("background-color:rgb(42,42,42)\n"
"")
        self.conLine.setReadOnly(True)
        self.conLine.setObjectName("conLine")
        self.gridLayout_4.addWidget(self.conLine, 0, 1, 1, 1)
        self.defaultCmb = QtWidgets.QComboBox(self.frame_3)
        self.defaultCmb.setMaximumSize(QtCore.QSize(16777215, 20))
        self.defaultCmb.setStyleSheet("background-color:rgb(42,42,42)\n"
"")
        self.defaultCmb.setObjectName("defaultCmb")
        self.gridLayout_4.addWidget(self.defaultCmb, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(180, 180, 180)")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setStyleSheet("")
        self.checkBox.setText("")
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.spaceTree_3 = QtWidgets.QTreeWidget(self.frame_3)
        self.spaceTree_3.setStyleSheet("background-color:rgb(42,42,42);\n"
"QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.spaceTree_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spaceTree_3.setDragEnabled(False)
        self.spaceTree_3.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.spaceTree_3.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.spaceTree_3.setAlternatingRowColors(True)
        self.spaceTree_3.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.spaceTree_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.spaceTree_3.setUniformRowHeights(True)
        self.spaceTree_3.setAllColumnsShowFocus(True)
        self.spaceTree_3.setColumnCount(3)
        self.spaceTree_3.setObjectName("spaceTree_3")
        self.spaceTree_3.headerItem().setText(0, "  Label")
        self.spaceTree_3.headerItem().setText(1, "Space Node")
        self.spaceTree_3.header().setVisible(True)
        self.spaceTree_3.header().setCascadingSectionResizes(True)
        self.spaceTree_3.header().setDefaultSectionSize(50)
        self.spaceTree_3.header().setMinimumSectionSize(50)
        self.spaceTree_3.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.spaceTree_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(2, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addSpaceBtgn_3 = QtWidgets.QPushButton(self.frame_3)
        self.addSpaceBtgn_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.addSpaceBtgn_3.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.addSpaceBtgn_3.setObjectName("addSpaceBtgn_3")
        self.horizontalLayout.addWidget(self.addSpaceBtgn_3)
        self.rmSpaceBtn_3 = QtWidgets.QPushButton(self.frame_3)
        self.rmSpaceBtn_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.rmSpaceBtn_3.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.rmSpaceBtn_3.setObjectName("rmSpaceBtn_3")
        self.horizontalLayout.addWidget(self.rmSpaceBtn_3)
        self.rmSpaceBtn_4 = QtWidgets.QPushButton(self.frame_3)
        self.rmSpaceBtn_4.setMaximumSize(QtCore.QSize(35, 20))
        self.rmSpaceBtn_4.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.rmSpaceBtn_4.setObjectName("rmSpaceBtn_4")
        self.horizontalLayout.addWidget(self.rmSpaceBtn_4)
        self.rmSpaceBtn_6 = QtWidgets.QPushButton(self.frame_3)
        self.rmSpaceBtn_6.setMaximumSize(QtCore.QSize(35, 20))
        self.rmSpaceBtn_6.setStyleSheet("QPushButton {background-color:rgb(80,80,80);}\n"
"")
        self.rmSpaceBtn_6.setObjectName("rmSpaceBtn_6")
        self.horizontalLayout.addWidget(self.rmSpaceBtn_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget)
        self.exportDeformersBtn = QtWidgets.QPushButton(tagToolsUI)
        self.exportDeformersBtn.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportDeformersBtn.setFont(font)
        self.exportDeformersBtn.setStyleSheet("background-color:rgb(128,128,128)")
        self.exportDeformersBtn.setObjectName("exportDeformersBtn")
        self.verticalLayout_4.addWidget(self.exportDeformersBtn)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 1)

        self.retranslateUi(tagToolsUI)
        QtCore.QObject.connect(self.tagSpaceBtn, QtCore.SIGNAL("clicked()"), self.tagKeyBtn.toggle)
        QtCore.QObject.connect(self.tagKeyBtn, QtCore.SIGNAL("clicked()"), self.tagSpaceBtn.toggle)
        QtCore.QObject.connect(self.tagSpaceBtn, QtCore.SIGNAL("clicked()"), self.widget.show)
        QtCore.QObject.connect(self.tagKeyBtn, QtCore.SIGNAL("clicked()"), self.widget.hide)
        QtCore.QObject.connect(self.tagKeyBtn, QtCore.SIGNAL("clicked()"), self.widget_2.show)
        QtCore.QObject.connect(self.tagSpaceBtn, QtCore.SIGNAL("clicked()"), self.widget_2.hide)
        QtCore.QMetaObject.connectSlotsByName(tagToolsUI)

    def retranslateUi(self, tagToolsUI):
        tagToolsUI.setWindowTitle(QtWidgets.QApplication.translate("tagToolsUI", "Tag Tools", None, -1))
        self.pathLabel.setText(QtWidgets.QApplication.translate("tagToolsUI", "Export Path", None, -1))
        self.browseBtn.setText(QtWidgets.QApplication.translate("tagToolsUI", "...", None, -1))
        self.tagKeyBtn.setText(QtWidgets.QApplication.translate("tagToolsUI", "Attributes", None, -1))
        self.tagSpaceBtn.setText(QtWidgets.QApplication.translate("tagToolsUI", "Spaces", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("tagToolsUI", "Tag Keyable Attributes    ", None, -1))
        self.addCtrlBtn_4.setText(QtWidgets.QApplication.translate("tagToolsUI", "+", None, -1))
        self.rmCtrlBtn_4.setText(QtWidgets.QApplication.translate("tagToolsUI", "-", None, -1))
        self.CBBtn_2.setText(QtWidgets.QApplication.translate("tagToolsUI", "Set From CB", None, -1))
        self.saveBtn_5.setText(QtWidgets.QApplication.translate("tagToolsUI", "Add From CB", None, -1))
        self.saveBtn_4.setText(QtWidgets.QApplication.translate("tagToolsUI", "Remove", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("tagToolsUI", "Tag Spaces    ", None, -1))
        self.addCtrlBtn_3.setText(QtWidgets.QApplication.translate("tagToolsUI", "+", None, -1))
        self.rmCtrlBtn_3.setText(QtWidgets.QApplication.translate("tagToolsUI", "-", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("tagToolsUI", "  Parent Node", None, -1))
        self.conBtn.setText(QtWidgets.QApplication.translate("tagToolsUI", "Get", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("tagToolsUI", "  Default Space", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("tagToolsUI", "  Rotation Only", None, -1))
        self.spaceTree_3.headerItem().setText(2, QtWidgets.QApplication.translate("tagToolsUI", "     ", None, -1))
        self.addSpaceBtgn_3.setText(QtWidgets.QApplication.translate("tagToolsUI", "Add", None, -1))
        self.rmSpaceBtn_3.setText(QtWidgets.QApplication.translate("tagToolsUI", "Remove", None, -1))
        self.rmSpaceBtn_4.setText(QtWidgets.QApplication.translate("tagToolsUI", "↑", None, -1))
        self.rmSpaceBtn_6.setText(QtWidgets.QApplication.translate("tagToolsUI", "↓", None, -1))
        self.exportDeformersBtn.setText(QtWidgets.QApplication.translate("tagToolsUI", "Export Tags", None, -1))

