# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DigitalFaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 787)
        MainWindow.setMinimumSize(QtCore.QSize(5, 5))
        MainWindow.setStyleSheet("font: 9pt \"Consolas\";\n"
"color: \"white\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(5, 5))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.temp_list = QtWidgets.QListWidget(self.tab_4)
        self.temp_list.setObjectName("temp_list")
        item = QtWidgets.QListWidgetItem()
        self.temp_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.temp_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.temp_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.temp_list.addItem(item)
        self.verticalLayout_6.addWidget(self.temp_list)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.replace_list = QtWidgets.QListWidget(self.tab_4)
        self.replace_list.setObjectName("replace_list")
        item = QtWidgets.QListWidgetItem()
        self.replace_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.replace_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.replace_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.replace_list.addItem(item)
        self.verticalLayout_9.addWidget(self.replace_list)
        self.horizontalLayout_12.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ImportBtn = QtWidgets.QPushButton(self.tab_4)
        self.ImportBtn.setObjectName("ImportBtn")
        self.horizontalLayout_11.addWidget(self.ImportBtn)
        self.match_btn = QtWidgets.QPushButton(self.tab_4)
        self.match_btn.setObjectName("match_btn")
        self.horizontalLayout_11.addWidget(self.match_btn)
        self.replace_btn = QtWidgets.QPushButton(self.tab_4)
        self.replace_btn.setObjectName("replace_btn")
        self.horizontalLayout_11.addWidget(self.replace_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.faceMdl_btn = QtWidgets.QPushButton(self.tab)
        self.faceMdl_btn.setObjectName("faceMdl_btn")
        self.horizontalLayout.addWidget(self.faceMdl_btn)
        self.faceMdl_le = QtWidgets.QLineEdit(self.tab)
        self.faceMdl_le.setReadOnly(True)
        self.faceMdl_le.setObjectName("faceMdl_le")
        self.horizontalLayout.addWidget(self.faceMdl_le)
        self.origMdl_btn = QtWidgets.QPushButton(self.tab)
        self.origMdl_btn.setObjectName("origMdl_btn")
        self.horizontalLayout.addWidget(self.origMdl_btn)
        self.origMdl_le = QtWidgets.QLineEdit(self.tab)
        self.origMdl_le.setObjectName("origMdl_le")
        self.horizontalLayout.addWidget(self.origMdl_le)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.typeCombo = QtWidgets.QComboBox(self.tab)
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.typeCombo)
        self.weightPath_le = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weightPath_le.setFont(font)
        self.weightPath_le.setReadOnly(True)
        self.weightPath_le.setObjectName("weightPath_le")
        self.horizontalLayout_2.addWidget(self.weightPath_le)
        self.weightPath_btn = QtWidgets.QPushButton(self.tab)
        self.weightPath_btn.setObjectName("weightPath_btn")
        self.horizontalLayout_2.addWidget(self.weightPath_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.create_btn = QtWidgets.QPushButton(self.tab)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_5.addWidget(self.create_btn)
        self.meshName_le = QtWidgets.QLineEdit(self.tab)
        self.meshName_le.setText("")
        self.meshName_le.setReadOnly(True)
        self.meshName_le.setObjectName("meshName_le")
        self.horizontalLayout_5.addWidget(self.meshName_le)
        self.export_btn = QtWidgets.QPushButton(self.tab)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_5.addWidget(self.export_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.doc_edit = QtWidgets.QLineEdit(self.tab)
        self.doc_edit.setReadOnly(True)
        self.doc_edit.setObjectName("doc_edit")
        self.verticalLayout_3.addWidget(self.doc_edit)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.treeViewBase = QtWidgets.QTreeView(self.tab)
        self.treeViewBase.setObjectName("treeViewBase")
        self.verticalLayout_4.addWidget(self.treeViewBase)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.value_dp = QtWidgets.QDoubleSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_dp.sizePolicy().hasHeightForWidth())
        self.value_dp.setSizePolicy(sizePolicy)
        self.value_dp.setMinimumSize(QtCore.QSize(0, 30))
        self.value_dp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_dp.setMaximum(1.0)
        self.value_dp.setSingleStep(0.001)
        self.value_dp.setProperty("value", 1.0)
        self.value_dp.setObjectName("value_dp")
        self.horizontalLayout_3.addWidget(self.value_dp)
        self.value_slider = QtWidgets.QSlider(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_slider.sizePolicy().hasHeightForWidth())
        self.value_slider.setSizePolicy(sizePolicy)
        self.value_slider.setMinimumSize(QtCore.QSize(0, 30))
        self.value_slider.setMaximum(100)
        self.value_slider.setProperty("value", 100)
        self.value_slider.setOrientation(QtCore.Qt.Horizontal)
        self.value_slider.setObjectName("value_slider")
        self.horizontalLayout_3.addWidget(self.value_slider)
        self.select_btn = QtWidgets.QPushButton(self.tab)
        self.select_btn.setObjectName("select_btn")
        self.horizontalLayout_3.addWidget(self.select_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.split_btn = QtWidgets.QPushButton(self.tab)
        self.split_btn.setObjectName("split_btn")
        self.horizontalLayout_4.addWidget(self.split_btn)
        self.ctrl_freezBtn = QtWidgets.QPushButton(self.tab)
        self.ctrl_freezBtn.setObjectName("ctrl_freezBtn")
        self.horizontalLayout_4.addWidget(self.ctrl_freezBtn)
        self.mirrorBtn = QtWidgets.QPushButton(self.tab)
        self.mirrorBtn.setObjectName("mirrorBtn")
        self.horizontalLayout_4.addWidget(self.mirrorBtn)
        self.autoMirror_cb = QtWidgets.QCheckBox(self.tab)
        self.autoMirror_cb.setObjectName("autoMirror_cb")
        self.horizontalLayout_4.addWidget(self.autoMirror_cb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.addBs_btn = QtWidgets.QPushButton(self.tab)
        self.addBs_btn.setObjectName("addBs_btn")
        self.horizontalLayout_13.addWidget(self.addBs_btn)
        self.mirrorLR = QtWidgets.QPushButton(self.tab)
        self.mirrorLR.setObjectName("mirrorLR")
        self.horizontalLayout_13.addWidget(self.mirrorLR)
        self.mirrorRL = QtWidgets.QPushButton(self.tab)
        self.mirrorRL.setObjectName("mirrorRL")
        self.horizontalLayout_13.addWidget(self.mirrorRL)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comBineViewBase = QtWidgets.QTreeView(self.tab_2)
        self.comBineViewBase.setObjectName("comBineViewBase")
        self.verticalLayout_5.addWidget(self.comBineViewBase)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.value_dp2 = QtWidgets.QDoubleSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_dp2.sizePolicy().hasHeightForWidth())
        self.value_dp2.setSizePolicy(sizePolicy)
        self.value_dp2.setMinimumSize(QtCore.QSize(0, 30))
        self.value_dp2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.value_dp2.setMaximum(1.0)
        self.value_dp2.setSingleStep(0.001)
        self.value_dp2.setProperty("value", 1.0)
        self.value_dp2.setObjectName("value_dp2")
        self.horizontalLayout_10.addWidget(self.value_dp2)
        self.value_slider2 = QtWidgets.QSlider(self.tab_2)
        self.value_slider2.setMaximum(1000)
        self.value_slider2.setSliderPosition(1000)
        self.value_slider2.setOrientation(QtCore.Qt.Horizontal)
        self.value_slider2.setObjectName("value_slider2")
        self.horizontalLayout_10.addWidget(self.value_slider2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shaderPath_btn = QtWidgets.QPushButton(self.tab_3)
        self.shaderPath_btn.setObjectName("shaderPath_btn")
        self.verticalLayout_2.addWidget(self.shaderPath_btn)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.diffuse_mapBtn = QtWidgets.QPushButton(self.tab_3)
        self.diffuse_mapBtn.setObjectName("diffuse_mapBtn")
        self.horizontalLayout_6.addWidget(self.diffuse_mapBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.diffuse_mapLe = QtWidgets.QLineEdit(self.tab_3)
        self.diffuse_mapLe.setReadOnly(True)
        self.diffuse_mapLe.setObjectName("diffuse_mapLe")
        self.horizontalLayout_6.addWidget(self.diffuse_mapLe)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.normal_mapBtn = QtWidgets.QPushButton(self.tab_3)
        self.normal_mapBtn.setObjectName("normal_mapBtn")
        self.horizontalLayout_7.addWidget(self.normal_mapBtn)
        spacerItem5 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.normal_mapLe = QtWidgets.QLineEdit(self.tab_3)
        self.normal_mapLe.setReadOnly(True)
        self.normal_mapLe.setObjectName("normal_mapLe")
        self.horizontalLayout_7.addWidget(self.normal_mapLe)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.wrinkleColor_btn = QtWidgets.QPushButton(self.tab_3)
        self.wrinkleColor_btn.setObjectName("wrinkleColor_btn")
        self.horizontalLayout_8.addWidget(self.wrinkleColor_btn)
        spacerItem6 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.wrinkleColor_le = QtWidgets.QLineEdit(self.tab_3)
        self.wrinkleColor_le.setReadOnly(True)
        self.wrinkleColor_le.setObjectName("wrinkleColor_le")
        self.horizontalLayout_8.addWidget(self.wrinkleColor_le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.wrinkleNormal_btn = QtWidgets.QPushButton(self.tab_3)
        self.wrinkleNormal_btn.setObjectName("wrinkleNormal_btn")
        self.horizontalLayout_9.addWidget(self.wrinkleNormal_btn)
        self.wrinkleNormal_le = QtWidgets.QLineEdit(self.tab_3)
        self.wrinkleNormal_le.setReadOnly(True)
        self.wrinkleNormal_le.setObjectName("wrinkleNormal_le")
        self.horizontalLayout_9.addWidget(self.wrinkleNormal_le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.mask_btn = QtWidgets.QPushButton(self.tab_3)
        self.mask_btn.setObjectName("mask_btn")
        self.verticalLayout_2.addWidget(self.mask_btn)
        self.anim_btn = QtWidgets.QPushButton(self.tab_3)
        self.anim_btn.setObjectName("anim_btn")
        self.verticalLayout_2.addWidget(self.anim_btn)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.toolBox = QtWidgets.QToolBox(self.tab_5)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 393, 523))
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lBr_btn = QtWidgets.QPushButton(self.page)
        self.lBr_btn.setObjectName("lBr_btn")
        self.horizontalLayout_15.addWidget(self.lBr_btn)
        self.rBr_btn = QtWidgets.QPushButton(self.page)
        self.rBr_btn.setObjectName("rBr_btn")
        self.horizontalLayout_15.addWidget(self.rBr_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lUplash_btn = QtWidgets.QPushButton(self.page)
        self.lUplash_btn.setObjectName("lUplash_btn")
        self.horizontalLayout_16.addWidget(self.lUplash_btn)
        self.rUplash_btn = QtWidgets.QPushButton(self.page)
        self.rUplash_btn.setObjectName("rUplash_btn")
        self.horizontalLayout_16.addWidget(self.rUplash_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lDnlash_btn = QtWidgets.QPushButton(self.page)
        self.lDnlash_btn.setObjectName("lDnlash_btn")
        self.horizontalLayout_17.addWidget(self.lDnlash_btn)
        self.rDnlash_btn = QtWidgets.QPushButton(self.page)
        self.rDnlash_btn.setObjectName("rDnlash_btn")
        self.horizontalLayout_17.addWidget(self.rDnlash_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        spacerItem8 = QtWidgets.QSpacerItem(20, 387, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 393, 578))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lUpshadow_btn = QtWidgets.QPushButton(self.page_2)
        self.lUpshadow_btn.setObjectName("lUpshadow_btn")
        self.horizontalLayout_18.addWidget(self.lUpshadow_btn)
        self.rUpshadow_btn = QtWidgets.QPushButton(self.page_2)
        self.rUpshadow_btn.setObjectName("rUpshadow_btn")
        self.horizontalLayout_18.addWidget(self.rUpshadow_btn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lDnshadow_btn = QtWidgets.QPushButton(self.page_2)
        self.lDnshadow_btn.setObjectName("lDnshadow_btn")
        self.horizontalLayout_19.addWidget(self.lDnshadow_btn)
        self.rDnshadow_btn = QtWidgets.QPushButton(self.page_2)
        self.rDnshadow_btn.setObjectName("rDnshadow_btn")
        self.horizontalLayout_19.addWidget(self.rDnshadow_btn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        spacerItem9 = QtWidgets.QSpacerItem(20, 479, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.face_update_btn = QtWidgets.QPushButton(self.page_3)
        self.face_update_btn.setObjectName("face_update_btn")
        self.verticalLayout_12.addWidget(self.face_update_btn)
        self.changeShape_btn = QtWidgets.QPushButton(self.page_3)
        self.changeShape_btn.setObjectName("changeShape_btn")
        self.verticalLayout_12.addWidget(self.changeShape_btn)
        self.follicleScl_btn = QtWidgets.QPushButton(self.page_3)
        self.follicleScl_btn.setObjectName("follicleScl_btn")
        self.verticalLayout_12.addWidget(self.follicleScl_btn)
        self.exp_btn = QtWidgets.QPushButton(self.page_3)
        self.exp_btn.setObjectName("exp_btn")
        self.verticalLayout_12.addWidget(self.exp_btn)
        spacerItem10 = QtWidgets.QSpacerItem(20, 358, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem10)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.createSec_btn = QtWidgets.QPushButton(self.page_4)
        self.createSec_btn.setObjectName("createSec_btn")
        self.verticalLayout_13.addWidget(self.createSec_btn)
        self.ctrlMir_btn = QtWidgets.QPushButton(self.page_4)
        self.ctrlMir_btn.setObjectName("ctrlMir_btn")
        self.verticalLayout_13.addWidget(self.ctrlMir_btn)
        self.selectCtrl_btn = QtWidgets.QPushButton(self.page_4)
        self.selectCtrl_btn.setObjectName("selectCtrl_btn")
        self.verticalLayout_13.addWidget(self.selectCtrl_btn)
        self.ImpWeight_btn = QtWidgets.QPushButton(self.page_4)
        self.ImpWeight_btn.setObjectName("ImpWeight_btn")
        self.verticalLayout_13.addWidget(self.ImpWeight_btn)
        spacerItem11 = QtWidgets.QSpacerItem(20, 413, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem11)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ShowLoc_btn = QtWidgets.QPushButton(self.page_5)
        self.ShowLoc_btn.setObjectName("ShowLoc_btn")
        self.horizontalLayout_20.addWidget(self.ShowLoc_btn)
        self.HideLoc_btn = QtWidgets.QPushButton(self.page_5)
        self.HideLoc_btn.setObjectName("HideLoc_btn")
        self.horizontalLayout_20.addWidget(self.HideLoc_btn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ExpBs_btn = QtWidgets.QPushButton(self.page_5)
        self.ExpBs_btn.setObjectName("ExpBs_btn")
        self.horizontalLayout_21.addWidget(self.ExpBs_btn)
        self.ImBs_btn = QtWidgets.QPushButton(self.page_5)
        self.ImBs_btn.setObjectName("ImBs_btn")
        self.horizontalLayout_21.addWidget(self.ImBs_btn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.splitAll_btn = QtWidgets.QPushButton(self.page_5)
        self.splitAll_btn.setObjectName("splitAll_btn")
        self.horizontalLayout_22.addWidget(self.splitAll_btn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        spacerItem12 = QtWidgets.QSpacerItem(20, 387, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem12)
        self.toolBox.addItem(self.page_5, "")
        self.verticalLayout_7.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionWd = QtWidgets.QAction(MainWindow)
        self.actionWd.setObjectName("actionWd")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionSmooth = QtWidgets.QAction(MainWindow)
        self.actionSmooth.setObjectName("actionSmooth")
        self.actionWeight = QtWidgets.QAction(MainWindow)
        self.actionWeight.setObjectName("actionWeight")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionEx = QtWidgets.QAction(MainWindow)
        self.actionEx.setObjectName("actionEx")
        self.actionLock = QtWidgets.QAction(MainWindow)
        self.actionLock.setObjectName("actionLock")
        self.actionShow = QtWidgets.QAction(MainWindow)
        self.actionShow.setObjectName("actionShow")
        self.actionHide = QtWidgets.QAction(MainWindow)
        self.actionHide.setObjectName("actionHide")
        self.actionMouthSec = QtWidgets.QAction(MainWindow)
        self.actionMouthSec.setObjectName("actionMouthSec")
        self.actionLeftBrow = QtWidgets.QAction(MainWindow)
        self.actionLeftBrow.setObjectName("actionLeftBrow")
        self.actionRightBrow = QtWidgets.QAction(MainWindow)
        self.actionRightBrow.setObjectName("actionRightBrow")
        self.actionLeftEyelashUp = QtWidgets.QAction(MainWindow)
        self.actionLeftEyelashUp.setObjectName("actionLeftEyelashUp")
        self.actionLeftEyelashDn = QtWidgets.QAction(MainWindow)
        self.actionLeftEyelashDn.setObjectName("actionLeftEyelashDn")
        self.actionRightEyelashUp = QtWidgets.QAction(MainWindow)
        self.actionRightEyelashUp.setObjectName("actionRightEyelashUp")
        self.actionRightEyelashDn = QtWidgets.QAction(MainWindow)
        self.actionRightEyelashDn.setObjectName("actionRightEyelashDn")
        self.actionLeftShadowUp = QtWidgets.QAction(MainWindow)
        self.actionLeftShadowUp.setObjectName("actionLeftShadowUp")
        self.actionLeftShadowDn = QtWidgets.QAction(MainWindow)
        self.actionLeftShadowDn.setObjectName("actionLeftShadowDn")
        self.actionRightShadowUp = QtWidgets.QAction(MainWindow)
        self.actionRightShadowUp.setObjectName("actionRightShadowUp")
        self.actionRightShadowDn = QtWidgets.QAction(MainWindow)
        self.actionRightShadowDn.setObjectName("actionRightShadowDn")
        self.actionSelectShadowJoints = QtWidgets.QAction(MainWindow)
        self.actionSelectShadowJoints.setObjectName("actionSelectShadowJoints")
        self.actionSelectDnShadowJoints = QtWidgets.QAction(MainWindow)
        self.actionSelectDnShadowJoints.setObjectName("actionSelectDnShadowJoints")
        self.actionFaceUpdate = QtWidgets.QAction(MainWindow)
        self.actionFaceUpdate.setObjectName("actionFaceUpdate")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionFollicCost = QtWidgets.QAction(MainWindow)
        self.actionFollicCost.setObjectName("actionFollicCost")
        self.actionCreateSec = QtWidgets.QAction(MainWindow)
        self.actionCreateSec.setObjectName("actionCreateSec")
        self.actionMirrorSec = QtWidgets.QAction(MainWindow)
        self.actionMirrorSec.setObjectName("actionMirrorSec")
        self.actionSelectSec = QtWidgets.QAction(MainWindow)
        self.actionSelectSec.setObjectName("actionSelectSec")
        self.actionImportSkin = QtWidgets.QAction(MainWindow)
        self.actionImportSkin.setObjectName("actionImportSkin")
        self.actionSplit_All_Targets = QtWidgets.QAction(MainWindow)
        self.actionSplit_All_Targets.setObjectName("actionSplit_All_Targets")
        self.actionTopology_TType = QtWidgets.QAction(MainWindow)
        self.actionTopology_TType.setObjectName("actionTopology_TType")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Teplate Mesh"))
        __sortingEnabled = self.temp_list.isSortingEnabled()
        self.temp_list.setSortingEnabled(False)
        item = self.temp_list.item(0)
        item.setText(_translate("MainWindow", "Head_mdl"))
        item = self.temp_list.item(1)
        item.setText(_translate("MainWindow", "L_Eyeball"))
        item = self.temp_list.item(2)
        item.setText(_translate("MainWindow", "R_Eyeball"))
        item = self.temp_list.item(3)
        item.setText(_translate("MainWindow", "Teeth"))
        self.temp_list.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Replace Mesh"))
        __sortingEnabled = self.replace_list.isSortingEnabled()
        self.replace_list.setSortingEnabled(False)
        item = self.replace_list.item(0)
        item.setText(_translate("MainWindow", "Head_mdl"))
        item = self.replace_list.item(1)
        item.setText(_translate("MainWindow", "L_Eyeball"))
        item = self.replace_list.item(2)
        item.setText(_translate("MainWindow", "R_Eyeball"))
        item = self.replace_list.item(3)
        item.setText(_translate("MainWindow", "Teeth"))
        self.replace_list.setSortingEnabled(__sortingEnabled)
        self.ImportBtn.setText(_translate("MainWindow", "Import Template"))
        self.match_btn.setText(_translate("MainWindow", "Auto Match"))
        self.replace_btn.setText(_translate("MainWindow", "Replace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Geometry"))
        self.faceMdl_btn.setText(_translate("MainWindow", "Face Model"))
        self.faceMdl_le.setText(_translate("MainWindow", "head_mdl"))
        self.origMdl_btn.setText(_translate("MainWindow", "Orig Model"))
        self.origMdl_le.setText(_translate("MainWindow", "org"))
        self.typeCombo.setItemText(0, _translate("MainWindow", "Meta"))
        self.typeCombo.setItemText(1, _translate("MainWindow", "Snapper"))
        self.weightPath_le.setText(_translate("MainWindow", "R:\\TeamCode\\OF3D_RIG\\modules\\scripts\\python\\Faith\\tools\\FacsTool\\faceDataV1"))
        self.weightPath_btn.setText(_translate("MainWindow", "WeightDataPath"))
        self.create_btn.setText(_translate("MainWindow", "Create BS Mesh"))
        self.export_btn.setText(_translate("MainWindow", "Export"))
        self.select_btn.setText(_translate("MainWindow", "Select"))
        self.split_btn.setText(_translate("MainWindow", "Split"))
        self.ctrl_freezBtn.setText(_translate("MainWindow", "Restore"))
        self.mirrorBtn.setText(_translate("MainWindow", "Mirror(Add)"))
        self.autoMirror_cb.setText(_translate("MainWindow", "Auto Mirror"))
        self.addBs_btn.setText(_translate("MainWindow", "Add BS"))
        self.mirrorLR.setText(_translate("MainWindow", "Mirror(L-->R)"))
        self.mirrorRL.setText(_translate("MainWindow", "Mirror(R-->L)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sculpt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Combine Shape"))
        self.shaderPath_btn.setText(_translate("MainWindow", "DX11 Material Path"))
        self.diffuse_mapBtn.setText(_translate("MainWindow", "diffuse map"))
        self.normal_mapBtn.setText(_translate("MainWindow", "normal map"))
        self.wrinkleColor_btn.setText(_translate("MainWindow", "wrinkle map"))
        self.wrinkleNormal_btn.setText(_translate("MainWindow", "wrinkle normal"))
        self.mask_btn.setText(_translate("MainWindow", "Face Controller Connect To DX11 Mask"))
        self.anim_btn.setText(_translate("MainWindow", "Add Wrinkle Attribute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "DX11"))
        self.lBr_btn.setText(_translate("MainWindow", "LSide Brow(12)"))
        self.rBr_btn.setText(_translate("MainWindow", "RSide Brow(12)"))
        self.lUplash_btn.setText(_translate("MainWindow", "LSide UpEyelash(12)"))
        self.rUplash_btn.setText(_translate("MainWindow", "RSide UpEyelash(12)"))
        self.lDnlash_btn.setText(_translate("MainWindow", "LSide DnEyelash(12)"))
        self.rDnlash_btn.setText(_translate("MainWindow", "RSide DnEyelash(12)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Brows And Eyelashes"))
        self.lUpshadow_btn.setText(_translate("MainWindow", "LSide UpShadows(5)"))
        self.rUpshadow_btn.setText(_translate("MainWindow", "RSide UpShadows(5)"))
        self.lDnshadow_btn.setText(_translate("MainWindow", "LSide DnShadows(5)"))
        self.rDnshadow_btn.setText(_translate("MainWindow", "RSide DnShadows(5)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Eyeballs And Shadows"))
        self.face_update_btn.setText(_translate("MainWindow", "Face Update"))
        self.changeShape_btn.setText(_translate("MainWindow", "Change Controller Shape"))
        self.follicleScl_btn.setText(_translate("MainWindow", "Follicle ScaleConstraint"))
        self.exp_btn.setText(_translate("MainWindow", "Create Double Movement Exp"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Face Update"))
        self.createSec_btn.setText(_translate("MainWindow", "Create Second Controllers"))
        self.ctrlMir_btn.setText(_translate("MainWindow", "Controllers Mirror L>>R"))
        self.selectCtrl_btn.setText(_translate("MainWindow", "Seclect Second Controllers"))
        self.ImpWeight_btn.setText(_translate("MainWindow", "Import Skin Weights(Select Head Mesh)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Seccond Controllers"))
        self.ShowLoc_btn.setText(_translate("MainWindow", "Show Locator"))
        self.HideLoc_btn.setText(_translate("MainWindow", "Hide Locator"))
        self.ExpBs_btn.setText(_translate("MainWindow", "Export BS Weights"))
        self.ImBs_btn.setText(_translate("MainWindow", "Import BS Weights"))
        self.splitAll_btn.setText(_translate("MainWindow", "Split All Targets"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Others"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Second Control"))
        self.actionWd.setText(_translate("MainWindow", "Add driven target"))
        self.actionConnect.setText(_translate("MainWindow", "Connect face controllers"))
        self.actionSmooth.setText(_translate("MainWindow", "Smooth Ziva Weight"))
        self.actionWeight.setText(_translate("MainWindow", "Edit Ziva Weight"))
        self.actionCreate.setText(_translate("MainWindow", "Create expressions"))
        self.actionEx.setText(_translate("MainWindow", "Create double translation exp"))
        self.actionLock.setText(_translate("MainWindow", "Move joints,Lock mesh"))
        self.actionShow.setText(_translate("MainWindow", "Show Locator"))
        self.actionHide.setText(_translate("MainWindow", "Hide Locator"))
        self.actionMouthSec.setText(_translate("MainWindow", "Add mouth sec controllers"))
        self.actionLeftBrow.setText(_translate("MainWindow", "LSide Brow(12)"))
        self.actionRightBrow.setText(_translate("MainWindow", "RSide Brow(12)"))
        self.actionLeftEyelashUp.setText(_translate("MainWindow", "LSide UpEyelash(12)"))
        self.actionLeftEyelashDn.setText(_translate("MainWindow", "LSide DnEyelash(12)"))
        self.actionRightEyelashUp.setText(_translate("MainWindow", "RSide UpEyelash(12)"))
        self.actionRightEyelashDn.setText(_translate("MainWindow", "RSide DnEyelash(12)"))
        self.actionLeftShadowUp.setText(_translate("MainWindow", "LSide UpShadow(5)"))
        self.actionLeftShadowDn.setText(_translate("MainWindow", "LSide DnShadow(5)"))
        self.actionRightShadowUp.setText(_translate("MainWindow", "RSide UpShadow(5)"))
        self.actionRightShadowDn.setText(_translate("MainWindow", "RSide DnShadow(5)"))
        self.actionSelectShadowJoints.setText(_translate("MainWindow", "Select Shadow Joints"))
        self.actionSelectDnShadowJoints.setText(_translate("MainWindow", "Select DnShadow Joints"))
        self.actionFaceUpdate.setText(_translate("MainWindow", "Update"))
        self.actionReplace.setText(_translate("MainWindow", "Controller Shape Change"))
        self.actionFollicCost.setText(_translate("MainWindow", "Follicle Scale Constrain"))
        self.actionCreateSec.setText(_translate("MainWindow", "Create Controllers"))
        self.actionMirrorSec.setText(_translate("MainWindow", "Mirror Controllers"))
        self.actionSelectSec.setText(_translate("MainWindow", "Select Sec Joints"))
        self.actionImportSkin.setText(_translate("MainWindow", "Import Weights"))
        self.actionSplit_All_Targets.setText(_translate("MainWindow", "Split All Targets"))
        self.actionTopology_TType.setText(_translate("MainWindow", "Topology Type"))


