# -*- coding: utf-8 -*-
import os, sys
from pymel.core import *
import json

pluginList = ["CorrectShape", "symmetry", "rampWeights", "weightsServer", "transferSkincluster"]
for plug in pluginList:
    if not pluginInfo(plug, q=True, loaded=True):
        try:
            loadPlugin(plug)
        except RuntimeError:
            error("You need the {0} plugins!".format(plug))


scriptPath = os.path.dirname(__file__).replace('/', '\\')
if sys.version_info.major >= 3:
    configPath = scriptPath + "\\faceDataV1\\poseData_py3.json"
else:
    configPath = scriptPath + "\\faceDataV1\\poseData_py2.json"

with open(configPath, 'r') as f:
    configData = json.load(f)

bsChannelList = [u'blink_brs_dn_in_l',
                 u'blink_brs_dn_in_r',
                 u'blink_brs_dn_out_l',
                 u'blink_brs_dn_out_r',
                 u'blink_brs_up_l',
                 u'blink_brs_up_r',
                 u'brows_dn_in_l',
                 u'brows_dn_in_r',
                 u'brows_dn_out_l',
                 u'brows_dn_out_r',
                 u'brows_squez_l',
                 u'brows_squez_r',
                 u'brows_squez_up',
                 u'brows_up_in_l',
                 u'brows_up_in_r',
                 u'brows_up_out_l',
                 u'brows_up_out_r',
                 u'cheek_raise_l',
                 u'cheek_raise_r',
                 u'chin_dn',
                 u'chin_up',
                 u'corners_close_l',
                 u'corners_close_r',
                 u'dimple_l',
                 u'dimple_r',
                 u'disgust_close_l',
                 u'disgust_close_r',
                 u'disgust_l',
                 u'disgust_r',
                 u'eye_blink_a_l',
                 u'eye_blink_a_r',
                 u'eye_blink_b_l',
                 u'eye_blink_b_r',
                 u'eye_blink_dn_l',
                 u'eye_blink_dn_r',
                 u'eye_blink_up_l',
                 u'eye_blink_up_r',
                 u'eye_look_dn_a_l',
                 u'eye_look_dn_a_r',
                 u'eye_look_dn_b_l',
                 u'eye_look_dn_b_r',
                 u'eye_look_in_l',
                 u'eye_look_in_r',
                 u'eye_look_out_l',
                 u'eye_look_out_r',
                 u'eye_look_up_l',
                 u'eye_look_up_r',
                 u'eye_squint_l',
                 u'eye_squint_r',
                 u'eye_sqz_l',
                 u'eye_sqz_r',
                 u'frown_l',
                 u'frown_r',
                 u'funel_l',
                 u'funel_r',
                 u'grin_drop_l',
                 u'grin_drop_r',
                 u'grin_l',
                 u'grin_r',
                 u'h_close_l',
                 u'h_close_r',
                 u'h_dn_drop_l',
                 u'h_dn_drop_r',
                 u'h_dn_l',
                 u'h_dn_r',
                 u'h_up_drop_l',
                 u'h_up_drop_r',
                 u'h_up_l',
                 u'h_up_r',
                 u'h_wide_l',
                 u'h_wide_r',
                 u'head_skin_slide',
                 u'jaw_back',
                 u'jaw_clench',
                 u'jaw_drop_old',
                 u'jaw_drop_mid_old',
                 u'jaw_fwd',
                 u'jaw_l',
                 u'jaw_r',
                 u'kiss_dn_l',
                 u'kiss_dn_r',
                 u'kiss_up_l',
                 u'kiss_up_r',
                 u'lip_lk_back_l',
                 u'lip_lk_back_r',
                 u'lip_lk_drop_l',
                 u'lip_lk_drop_mid_l',
                 u'lip_lk_drop_mid_r',
                 u'lip_lk_drop_r',
                 u'lip_lk_fwd_l',
                 u'lip_lk_fwd_r',
                 u'lip_lk_mov_l_l',
                 u'lip_lk_mov_l_r',
                 u'lip_lk_mov_r_l',
                 u'lip_lk_mov_r_r',
                 u'lwr_lid_dn_l',
                 u'lwr_lid_dn_r',
                 u'lwr_lid_up_l',
                 u'lwr_lid_up_r',
                 u'lwr_lip_back',
                 u'lwr_lip_dn_l',
                 u'lwr_lip_dn_r',
                 u'lwr_lip_in_drop_l',
                 u'lwr_lip_in_drop_r',
                 u'lwr_lip_in_l',
                 u'lwr_lip_in_r',
                 u'lwr_lip_mov_l',
                 u'lwr_lip_mov_r',
                 u'lwr_lip_out',
                 u'lwr_lip_volume',
                 u'm_1',
                 u'mouth_dn',
                 u'mouth_mov_l',
                 u'mouth_mov_r',
                 u'mouth_mov_up',
                 u'mouth_mov_up_2',
                 u'mouth_mov_up_3',
                 u'mouth_press',
                 u'mouth_tension',
                 u'neck_blow_l',
                 u'neck_blow_r',
                 u'neck_muscle_l',
                 u'neck_muscle_r',
                 u'neck_slide_l',
                 u'neck_slide_r',
                 u'neck_tension_l',
                 u'neck_tension_r',
                 u'nose_close',
                 u'nose_open',
                 u'o_dn_l',
                 u'o_dn_r',
                 u'o_up_l',
                 u'o_up_r',
                 u'o_wide_dn_l',
                 u'o_wide_dn_r',
                 u'o_wide_up_l',
                 u'o_wide_up_r',
                 u'puff_dn_l',
                 u'puff_dn_r',
                 u'puff_l',
                 u'puff_r',
                 u'puff_up_l',
                 u'puff_up_r',
                 u'pull_close_l',
                 u'pull_close_r',
                 u'pull_drop_l',
                 u'pull_drop_r',
                 u'pull_l',
                 u'pull_r',
                 u'smile_close_l',
                 u'smile_close_r',
                 u'smile_drop_l',
                 u'smile_drop_r',
                 u'smile_l',
                 u'smile_open_l',
                 u'smile_open_r',
                 u'smile_r',
                 u'sneer_close_l',
                 u'sneer_close_r',
                 u'sneer_only_l',
                 u'sneer_only_r',
                 u'sticky_lips_1_l',
                 u'sticky_lips_1_r',
                 u'sticky_lips_2_l',
                 u'sticky_lips_2_r',
                 u'sticky_lips_3_l',
                 u'sticky_lips_3_r',
                 u'sticky_lips_4_l',
                 u'sticky_lips_4_r',
                 u'sticky_lips_5_l',
                 u'sticky_lips_5_r',
                 u'sticky_lips_6_l',
                 u'sticky_lips_6_r',
                 u'stretch_l',
                 u'stretch_r',
                 u'suck_l',
                 u'suck_r',
                 u'swallow_1',
                 u'swallow_2',
                 u'swallow_3',
                 u'swallow_4',
                 u'swallow_5',
                 u'tension_drop_l',
                 u'tension_drop_r',
                 u'tight_l',
                 u'tight_r',
                 u'upr_lid_dn_a_l',
                 u'upr_lid_dn_a_r',
                 u'upr_lid_dn_b_l',
                 u'upr_lid_dn_b_r',
                 u'upr_lid_up_l',
                 u'upr_lid_up_r',
                 u'upr_lip_back',
                 u'upr_lip_funl_l',
                 u'upr_lip_funl_r',
                 u'upr_lip_in_l',
                 u'upr_lip_in_r',
                 u'upr_lip_up_drop_l',
                 u'upr_lip_up_drop_r',
                 u'upr_lip_up_l',
                 u'upr_lip_up_r',
                 u'upr_lip_volume',
                 u'blink_look_out_l',
                 u'blink_look_out_r',
                 u'look_dn_open_l',
                 u'look_dn_open_r',
                 u'turn_left',
                 u'turn_left_drop',
                 u'turn_dn',
                 u'turn_right',
                 u'turn_right_drop',
                 u'turn_up',
                 u'brows_spread_l',
                 u'brows_spread_r',
                 u'nose_dn',
                 u'upr_lip_tension',
                 u'jaw_drop',
                 u'jaw_drop_mid',
                 u'eye_look_in_mid_l',
                 u'eye_look_in_mid_r',
                 u'eye_look_out_mid_l',
                 u'eye_look_out_mid_r',
                 u'blink_brs_up_in_l',
                 u'blink_brs_up_in_r',
                 u'blink_brs_up_out_l',
                 u'blink_brs_up_out_r',
                 u'grin_pull_l',
                 u'grin_pull_r',
                 u'double_eyelid_dn_l',
                 u'double_eyelid_dn_r',
                 u'double_eyelid_up_l',
                 u'double_eyelid_up_r',
                 u'L_weidong_tar',
                 u'R_weidong_tar']

face_ctrls = [u'Head_cntr', u'Brow_cntr', u'BrowIn_L_cntr', u'BrowIn_R_cntr', u'BrowOut_L_cntr', u'BrowOut_R_cntr',
              u'UprLid_L_cntr', u'UprLid_R_cntr', u'EyeSqz_L_cntr', u'EyeSqz_R_cntr', u'LwrLid_L_cntr',
              u'LwrLid_R_cntr',
              u'Cheek_L_cntr', u'Cheek_R_cntr', u'Nose_L_cntr', u'Nose_R_cntr', u'Nose_cntr',
              u'UprLip_2_cntr', u'UprLip_cntr', u'UprLip_L_cntr', u'UprLip_R_cntr', u'UprLip_L_2_cntr',
              u'UprLip_R_2_cntr',
              u'Crnr_L_cntr', u'Crnr_R_cntr', u'Crnr_L_2_cntr', u'Crnr_R_2_cntr', u'Cheek_L_2_cntr', u'Cheek_R_2_cntr',
              u'LwrLip_L_cntr', u'LwrLip_R_cntr', u'Chin_L_cntr', u'Chin_R_cntr', u'LwrLip_cntr', u'Chin_cntr',
              u'Jaw_cntr',
              u'Mouth_cntr', u'Neck_cntr', u'Tongue_cntr', u'Tonge_roll_cntr', u'Tongue_tip_cntr',
              u'L_eye_ctrl', u'R_eye_ctrl']

face_sec_ctrls = ['L_Brow_1_sec_ctrl', 'L_Brow_2_sec_ctrl', 'L_Brow_3_sec_ctrl'
    , 'L_UprLid_1_sec_ctrl', 'L_UprLid_2_sec_ctrl', 'L_UprLid_3_sec_ctrl'
    , 'L_LwrLid_1_sec_ctrl', 'L_LwrLid_2_sec_ctrl', 'L_LwrLid_3_sec_ctrl'
    , 'L_UprLip_sec_ctrl', 'L_LwrLip_sec_ctrl', 'L_Corner_sec_ctrl'
    , 'L_UprLip02_sec_ctrl', 'L_LwrLip02_sec_ctrl'
    , 'UprLip_sec_ctrl', 'LwrLip_sec_ctrl'
    , 'R_Brow_1_sec_ctrl', 'R_Brow_2_sec_ctrl', 'R_Brow_3_sec_ctrl'
    , 'R_UprLid_1_sec_ctrl', 'R_UprLid_2_sec_ctrl', 'R_UprLid_3_sec_ctrl'
    , 'R_LwrLid_1_sec_ctrl', 'R_LwrLid_2_sec_ctrl', 'R_LwrLid_3_sec_ctrl'
    , 'R_UprLip_sec_ctrl', 'R_LwrLip_sec_ctrl', 'R_Corner_sec_ctrl'
    , 'R_UprLip02_sec_ctrl', 'R_LwrLip02_sec_ctrl']

secJnts = ['face_Head_base_jnt', 'L_Brow_1_sec_jnt', 'L_Brow_2_sec_jnt', 'L_Brow_3_sec_jnt',
           'L_UprLid_1_sec_jnt', 'L_UprLid_2_sec_jnt', 'L_UprLid_3_sec_jnt',
           'L_LwrLid_1_sec_jnt', 'L_LwrLid_2_sec_jnt', 'L_LwrLid_3_sec_jnt',
           'L_UprLip_sec_jnt', 'L_LwrLip_sec_jnt', 'L_Corner_sec_jnt',
           'R_Brow_1_sec_jnt', 'R_Brow_2_sec_jnt', 'R_Brow_3_sec_jnt',
           'R_UprLid_1_sec_jnt', 'R_UprLid_2_sec_jnt', 'R_UprLid_3_sec_jnt',
           'R_LwrLid_1_sec_jnt', 'R_LwrLid_2_sec_jnt', 'R_LwrLid_3_sec_jnt',
           'R_UprLip_sec_jnt', 'R_LwrLip_sec_jnt', 'R_Corner_sec_jnt',
           'UprLip_sec_jnt', 'LwrLip_sec_jnt']


def getPoseData(poseData, item):
    """

    @param poseData: config
    @return:
    """
    ctrlNames = poseData[item]["ctrlNames"]  # ������
    ctrlAttrs = poseData[item]["ctrlAttrs"]  # ����������
    ctrlValues = poseData[item]["ctrlValues"]  # ��������ֵ
    weightDataSplitList = poseData[item]["weightDataSplitList"]  # ����б�
    SplitweightList = poseData[item]["SplitweightList"]  # ���Ȩ��
    subFaces = poseData[item]["subFaces"]  # ��������
    subFaceValues = poseData[item]["subFaceValues"]  # ������ֵ
    doc = poseData[item]["doc"]
    return [ctrlNames, ctrlAttrs,
            ctrlValues, weightDataSplitList,
            SplitweightList, subFaces,
            subFaceValues, doc]


