# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\controllerUI.ui'
#
# Created: Fri Nov 10 10:52:48 2023
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ctrl_win(object):
    def setupUi(self, ctrl_win):
        ctrl_win.setObjectName("ctrl_win")
        ctrl_win.resize(380, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ctrl_win.sizePolicy().hasHeightForWidth())
        ctrl_win.setSizePolicy(sizePolicy)
        ctrl_win.setMinimumSize(QtCore.QSize(380, 750))
        self.gridLayout = QtWidgets.QGridLayout(ctrl_win)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(ctrl_win)
        self.frame.setMinimumSize(QtCore.QSize(0, 45))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("background-color:rgb(42,42,42);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(4, 2, 8, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.controlTools_label = QtWidgets.QLabel(self.frame)
        self.controlTools_label.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.controlTools_label.setFont(font)
        self.controlTools_label.setStyleSheet("color:lightGrey")
        self.controlTools_label.setIndent(10)
        self.controlTools_label.setObjectName("controlTools_label")
        self.horizontalLayout_3.addWidget(self.controlTools_label)
        self.controlTools_help = QtWidgets.QPushButton(self.frame)
        self.controlTools_help.setMaximumSize(QtCore.QSize(30, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rigBuild/icons/helpMeduim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlTools_help.setIcon(icon)
        self.controlTools_help.setFlat(True)
        self.controlTools_help.setObjectName("controlTools_help")
        self.horizontalLayout_3.addWidget(self.controlTools_help)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.shape_gb = QtWidgets.QGroupBox(ctrl_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shape_gb.sizePolicy().hasHeightForWidth())
        self.shape_gb.setSizePolicy(sizePolicy)
        self.shape_gb.setMinimumSize(QtCore.QSize(320, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.shape_gb.setFont(font)
        self.shape_gb.setFlat(False)
        self.shape_gb.setCheckable(False)
        self.shape_gb.setObjectName("shape_gb")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.shape_gb)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ctrl_listWidget = QtWidgets.QListWidget(self.shape_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_listWidget.sizePolicy().hasHeightForWidth())
        self.ctrl_listWidget.setSizePolicy(sizePolicy)
        self.ctrl_listWidget.setBaseSize(QtCore.QSize(272, 0))
        self.ctrl_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ctrl_listWidget.setIconSize(QtCore.QSize(70, 70))
        self.ctrl_listWidget.setMovement(QtWidgets.QListView.Static)
        self.ctrl_listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.ctrl_listWidget.setGridSize(QtCore.QSize(80, 80))
        self.ctrl_listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.ctrl_listWidget.setUniformItemSizes(False)
        self.ctrl_listWidget.setObjectName("ctrl_listWidget")
        self.gridLayout_6.addWidget(self.ctrl_listWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.shape_gb, 2, 0, 1, 1)
        self.create_gb = QtWidgets.QGroupBox(ctrl_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_gb.sizePolicy().hasHeightForWidth())
        self.create_gb.setSizePolicy(sizePolicy)
        self.create_gb.setMinimumSize(QtCore.QSize(0, 0))
        self.create_gb.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.create_gb.setFont(font)
        self.create_gb.setTitle("")
        self.create_gb.setObjectName("create_gb")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.create_gb)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.name_lb = QtWidgets.QLabel(self.create_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lb.sizePolicy().hasHeightForWidth())
        self.name_lb.setSizePolicy(sizePolicy)
        self.name_lb.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.name_lb.setFont(font)
        self.name_lb.setObjectName("name_lb")
        self.horizontalLayout_5.addWidget(self.name_lb)
        self.nameLine = QtWidgets.QLineEdit(self.create_gb)
        self.nameLine.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.nameLine.setFont(font)
        self.nameLine.setText("")
        self.nameLine.setObjectName("nameLine")
        self.horizontalLayout_5.addWidget(self.nameLine)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.hirerachy_cb = QtWidgets.QCheckBox(self.create_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hirerachy_cb.sizePolicy().hasHeightForWidth())
        self.hirerachy_cb.setSizePolicy(sizePolicy)
        self.hirerachy_cb.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hirerachy_cb.setFont(font)
        self.hirerachy_cb.setObjectName("hirerachy_cb")
        self.horizontalLayout_4.addWidget(self.hirerachy_cb)
        self.orient_cb = QtWidgets.QCheckBox(self.create_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orient_cb.sizePolicy().hasHeightForWidth())
        self.orient_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.orient_cb.setFont(font)
        self.orient_cb.setObjectName("orient_cb")
        self.horizontalLayout_4.addWidget(self.orient_cb)
        self.revcon_cb = QtWidgets.QCheckBox(self.create_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.revcon_cb.sizePolicy().hasHeightForWidth())
        self.revcon_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.revcon_cb.setFont(font)
        self.revcon_cb.setObjectName("revcon_cb")
        self.horizontalLayout_4.addWidget(self.revcon_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.create_gb, 1, 0, 1, 1)
        self.modify_gb = QtWidgets.QGroupBox(ctrl_win)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_gb.sizePolicy().hasHeightForWidth())
        self.modify_gb.setSizePolicy(sizePolicy)
        self.modify_gb.setMinimumSize(QtCore.QSize(0, 230))
        self.modify_gb.setMaximumSize(QtCore.QSize(16777215, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.modify_gb.setFont(font)
        self.modify_gb.setObjectName("modify_gb")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.modify_gb)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.seprate_line = QtWidgets.QFrame(self.modify_gb)
        self.seprate_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.seprate_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seprate_line.setObjectName("seprate_line")
        self.gridLayout_3.addWidget(self.seprate_line, 5, 0, 1, 1)
        self.seprate_line_3 = QtWidgets.QFrame(self.modify_gb)
        self.seprate_line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.seprate_line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seprate_line_3.setObjectName("seprate_line_3")
        self.gridLayout_3.addWidget(self.seprate_line_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sc_shape_btn = QtWidgets.QPushButton(self.modify_gb)
        self.sc_shape_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.sc_shape_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.sc_shape_btn.setFont(font)
        self.sc_shape_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.sc_shape_btn.setObjectName("sc_shape_btn")
        self.horizontalLayout_2.addWidget(self.sc_shape_btn)
        self.sc_object_btn = QtWidgets.QPushButton(self.modify_gb)
        self.sc_object_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.sc_object_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.sc_object_btn.setFont(font)
        self.sc_object_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.sc_object_btn.setObjectName("sc_object_btn")
        self.horizontalLayout_2.addWidget(self.sc_object_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.exportShape_btn = QtWidgets.QPushButton(self.modify_gb)
        self.exportShape_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.exportShape_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.exportShape_btn.setFont(font)
        self.exportShape_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.exportShape_btn.setObjectName("exportShape_btn")
        self.horizontalLayout_6.addWidget(self.exportShape_btn)
        self.importShape_btn = QtWidgets.QPushButton(self.modify_gb)
        self.importShape_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.importShape_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.importShape_btn.setFont(font)
        self.importShape_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.importShape_btn.setObjectName("importShape_btn")
        self.horizontalLayout_6.addWidget(self.importShape_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 8, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mirrorControl_btn = QtWidgets.QPushButton(self.modify_gb)
        self.mirrorControl_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.mirrorControl_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.mirrorControl_btn.setFont(font)
        self.mirrorControl_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mirrorControl_btn.setObjectName("mirrorControl_btn")
        self.horizontalLayout_8.addWidget(self.mirrorControl_btn)
        self.mirrorShapel_btn = QtWidgets.QPushButton(self.modify_gb)
        self.mirrorShapel_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.mirrorShapel_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.mirrorShapel_btn.setFont(font)
        self.mirrorShapel_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mirrorShapel_btn.setObjectName("mirrorShapel_btn")
        self.horizontalLayout_8.addWidget(self.mirrorShapel_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rox_btn = QtWidgets.QPushButton(self.modify_gb)
        self.rox_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.rox_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.rox_btn.setFont(font)
        self.rox_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.rox_btn.setObjectName("rox_btn")
        self.horizontalLayout_10.addWidget(self.rox_btn)
        self.roy_btn = QtWidgets.QPushButton(self.modify_gb)
        self.roy_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.roy_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.roy_btn.setFont(font)
        self.roy_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.roy_btn.setObjectName("roy_btn")
        self.horizontalLayout_10.addWidget(self.roy_btn)
        self.roz_btn = QtWidgets.QPushButton(self.modify_gb)
        self.roz_btn.setMinimumSize(QtCore.QSize(60, 23))
        self.roz_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.roz_btn.setFont(font)
        self.roz_btn.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.roz_btn.setObjectName("roz_btn")
        self.horizontalLayout_10.addWidget(self.roz_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 4, 0, 1, 1)
        self.sv_hl = QtWidgets.QHBoxLayout()
        self.sv_hl.setObjectName("sv_hl")
        self.sv_line = QtWidgets.QLineEdit(self.modify_gb)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.sv_line.setFont(font)
        self.sv_line.setObjectName("sv_line")
        self.sv_hl.addWidget(self.sv_line)
        self.s01_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s01_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s01_btn.setFont(font)
        self.s01_btn.setObjectName("s01_btn")
        self.sv_hl.addWidget(self.s01_btn)
        self.s05_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s05_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s05_btn.setFont(font)
        self.s05_btn.setObjectName("s05_btn")
        self.sv_hl.addWidget(self.s05_btn)
        self.s07_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s07_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s07_btn.setFont(font)
        self.s07_btn.setObjectName("s07_btn")
        self.sv_hl.addWidget(self.s07_btn)
        self.s09_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s09_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s09_btn.setFont(font)
        self.s09_btn.setObjectName("s09_btn")
        self.sv_hl.addWidget(self.s09_btn)
        self.s12_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s12_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s12_btn.setFont(font)
        self.s12_btn.setObjectName("s12_btn")
        self.sv_hl.addWidget(self.s12_btn)
        self.s15_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s15_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s15_btn.setFont(font)
        self.s15_btn.setObjectName("s15_btn")
        self.sv_hl.addWidget(self.s15_btn)
        self.s20_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.s20_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.s20_btn.setFont(font)
        self.s20_btn.setObjectName("s20_btn")
        self.sv_hl.addWidget(self.s20_btn)
        self.gridLayout_3.addLayout(self.sv_hl, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.green_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.green_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.green_color_btn.setFont(font)
        self.green_color_btn.setObjectName("green_color_btn")
        self.horizontalLayout.addWidget(self.green_color_btn)
        self.violet_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.violet_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.violet_color_btn.setFont(font)
        self.violet_color_btn.setObjectName("violet_color_btn")
        self.horizontalLayout.addWidget(self.violet_color_btn)
        self.red_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.red_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.red_color_btn.setFont(font)
        self.red_color_btn.setObjectName("red_color_btn")
        self.horizontalLayout.addWidget(self.red_color_btn)
        self.yellow_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.yellow_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.yellow_color_btn.setFont(font)
        self.yellow_color_btn.setObjectName("yellow_color_btn")
        self.horizontalLayout.addWidget(self.yellow_color_btn)
        self.blue_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.blue_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.blue_color_btn.setFont(font)
        self.blue_color_btn.setObjectName("blue_color_btn")
        self.horizontalLayout.addWidget(self.blue_color_btn)
        self.cobalt_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 110, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 110, 212))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.cobalt_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.cobalt_color_btn.setFont(font)
        self.cobalt_color_btn.setObjectName("cobalt_color_btn")
        self.horizontalLayout.addWidget(self.cobalt_color_btn)
        self.turquoise_color_btn = QtWidgets.QPushButton(self.modify_gb)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.turquoise_color_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.turquoise_color_btn.setFont(font)
        self.turquoise_color_btn.setObjectName("turquoise_color_btn")
        self.horizontalLayout.addWidget(self.turquoise_color_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.modify_gb)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 7, 0, 1, 1)
        self.gridLayout.addWidget(self.modify_gb, 3, 0, 1, 1)

        self.retranslateUi(ctrl_win)
        QtCore.QMetaObject.connectSlotsByName(ctrl_win)

    def retranslateUi(self, ctrl_win):
        ctrl_win.setWindowTitle(QtWidgets.QApplication.translate("ctrl_win", "ControlTools", None, -1))
        self.controlTools_label.setText(QtWidgets.QApplication.translate("ctrl_win", "Control Tools", None, -1))
        self.shape_gb.setTitle(QtWidgets.QApplication.translate("ctrl_win", "Create", None, -1))
        self.name_lb.setText(QtWidgets.QApplication.translate("ctrl_win", "Name  ", None, -1))
        self.hirerachy_cb.setText(QtWidgets.QApplication.translate("ctrl_win", "Hirerachy", None, -1))
        self.orient_cb.setText(QtWidgets.QApplication.translate("ctrl_win", "Orient", None, -1))
        self.revcon_cb.setText(QtWidgets.QApplication.translate("ctrl_win", "RevConstraint", None, -1))
        self.modify_gb.setTitle(QtWidgets.QApplication.translate("ctrl_win", "Modify", None, -1))
        self.sc_shape_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Scale (shape center)", None, -1))
        self.sc_object_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Scale (object center)", None, -1))
        self.exportShape_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Export Shape", None, -1))
        self.importShape_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Import Shape", None, -1))
        self.mirrorControl_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Mirror Control", None, -1))
        self.mirrorShapel_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Mirror Shape", None, -1))
        self.rox_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Ro-X", None, -1))
        self.roy_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Ro-Y", None, -1))
        self.roz_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Ro-Z", None, -1))
        self.sv_line.setText(QtWidgets.QApplication.translate("ctrl_win", "0.1", None, -1))
        self.s01_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "0.1", None, -1))
        self.s05_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "0.5", None, -1))
        self.s07_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "0.7", None, -1))
        self.s09_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "0.9", None, -1))
        self.s12_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "1.2", None, -1))
        self.s15_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "1.5", None, -1))
        self.s20_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "2.0", None, -1))
        self.green_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "G", None, -1))
        self.violet_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "V", None, -1))
        self.red_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "R", None, -1))
        self.yellow_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "Y", None, -1))
        self.blue_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "B", None, -1))
        self.cobalt_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "C", None, -1))
        self.turquoise_color_btn.setText(QtWidgets.QApplication.translate("ctrl_win", "T", None, -1))

