# named graph constants
from cgrig.libs.maya.utils import mayaenv

MAYA_VERSION = mayaenv.mayaVersion()
greaterMayaVersion2023 = mayaenv.mayaVersion() >= 2023
greaterMayaVersion2026 = mayaenv.mayaVersion() >= 2026

# internal graph ids which are swapped based on maya version
kAngleBetweenBlend = "angleBetweenBlend"
kBendyMotionPath = "bendyMotionPath"
kBendySegmentEndTangentRot = "bendySegmentEndTangentRotPre2023"
kBendySquash = "bendySquash"
kBendyTangent = "bendyTangentPre2023"
kMidSegmentPointRoundness = "midSegmentPointRoundnessPre2023"
kPrimaryMidBendyCtrls = "primaryMidBendyCtrlsPre2023"
kPrimaryMidBendyRoundness = "primaryMidBendyRoundness"
kBrowInnerCtrlOut = "browInnerCtrlOut"
kBrowMidCtrlOut = "browMidCtrlOut"
kBrowMidPointNoRot = "browMidPointNoRotPre2023"
kBrowOuterCtrlOut = "browOuterCtrlOut"
kBrowRail = "browRail"
kBrowRailMid = "browRailMid"
kJointConstraint = "jointConstraint"
kJointRailOut = "jointRailOut"
kJawDifferentiatorBS = "jawDifferentiatorBS"
kAutoPoleVector = "autoPoleVector"
kIkGlobalStretch = "ikGlobalStretch"
kIkGlobalStretchNeg = "ikGlobalStretchNeg"
kIkGlobalStretchQuad = "ikGlobalStretchQuad"
kIkGlobalStretchQuadNeg = "ikGlobalStretchQuadNeg"
kIkSegmentScaleStretch = "ikSegmentScaleStretch"
kIkSegmentScaleStretchNeg = "ikSegmentScaleStretchNeg"
kPerpendicularVectorNegative = "perpendicularVectorNegative"
kQuadAnkleIkSegmentScaleStretch = "quadAnkleIkSegmentScaleStretch"
kDistributedTwist = "distributedTwist"
kDistributedTwistNeg = "distributedTwistNeg"
kTwistGuideAlign = "twistGuideAlignPre2023"
kTwistOffsetCtrl = "twistOffsetCtrl"
kTwistOffsetCtrlRotation = "twistOffsetCtrlRotation"
kJawMover = "jawMover"
kMotionPathGuide = "motionPathGuide"
kMotionPathCns = "motionPathCns"
klipZipper = "lipZipper"
kMotionPathLipCtrl = "motionPathLipCtrl"
kMotionPathSecondaryCtrls = "motionPathSecondaryCtrls"
kBlendedJointRot = "blendedJointRot"
kLwrMouthFourWayProxyPin = "lwrMouthFourWayProxyPin"
kMotionPathLipCtrlTangents = "motionPathLipCtrlTangents"
kMouthFourWayProxyPin = "mouthFourWayProxyPin"
kCheekLocalMultiplier = "cheekLocalMultiplier"
kLipPSD = "lipPSD"
if greaterMayaVersion2023:
    kBendySegmentEndTangentRot = "bendySegmentEndTangentRot"
    kBendyTangent = "bendyTangent"
    kMidSegmentPointRoundness = "midSegmentPointRoundness"
    kPrimaryMidBendyCtrls = "primaryMidBendyCtrls"
    kBrowMidPointNoRot = "browMidPointNoRot"
    kTwistGuideAlign = "twistGuideAlign"

if greaterMayaVersion2026:
    kAngleBetweenBlend = "angleBetweenBlend2026"
    kBendySegmentEndTangentRot = "bendySegmentEndTangentRot2026"
    kBendySquash = "bendySquash2026"
    kBendyTangent = "bendyTangent2026"
    kPrimaryMidBendyCtrls = "primaryMidBendyCtrls2026"
    kPrimaryMidBendyRoundness = "primaryMidBendyRoundness2026"
    kIkGlobalStretch = "ikGlobalStretch2026"
    kIkGlobalStretchNeg = "ikGlobalStretchNeg2026"
    kIkGlobalStretchQuad = "ikGlobalStretchQuad2026"
    kIkGlobalStretchQuadNeg = "ikGlobalStretchQuadNeg2026"
    kIkSegmentScaleStretch = "ikSegmentScaleStretch2026"
    kIkSegmentScaleStretchNeg = "ikSegmentScaleStretchNeg2026"
    kQuadAnkleIkSegmentScaleStretch = "quadAnkleIkSegmentScaleStretch2026"
    kTwistOffsetCtrlRotation = "twistOffsetCtrlRotation2026"
    kJawMover = "jawMover2026"
    klipZipper = "lipZipper2026"
