# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helperUI.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from vendor.Qt import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoadHz = QtWidgets.QHBoxLayout()
        self.LoadHz.setObjectName("LoadHz")
        self.LoadPb = QtWidgets.QPushButton(self.centralwidget)
        self.LoadPb.setObjectName("LoadPb")
        self.LoadHz.addWidget(self.LoadPb)
        self.LoadLe = QtWidgets.QLineEdit(self.centralwidget)
        self.LoadLe.setReadOnly(True)
        self.LoadLe.setObjectName("LoadLe")
        self.LoadHz.addWidget(self.LoadLe)
        self.ParentPb = QtWidgets.QPushButton(self.centralwidget)
        self.ParentPb.setObjectName("ParentPb")
        self.LoadHz.addWidget(self.ParentPb)
        self.ParentLe = QtWidgets.QLineEdit(self.centralwidget)
        self.ParentLe.setReadOnly(True)
        self.ParentLe.setObjectName("ParentLe")
        self.LoadHz.addWidget(self.ParentLe)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.LoadHz.addWidget(self.label)
        self.side_cb = QtWidgets.QComboBox(self.centralwidget)
        self.side_cb.setObjectName("side_cb")
        self.side_cb.addItem("")
        self.side_cb.addItem("")
        self.side_cb.addItem("")
        self.LoadHz.addWidget(self.side_cb)
        self.verticalLayout.addLayout(self.LoadHz)
        self.AxisHz = QtWidgets.QHBoxLayout()
        self.AxisHz.setObjectName("AxisHz")
        self.RoLb = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoLb.sizePolicy().hasHeightForWidth())
        self.RoLb.setSizePolicy(sizePolicy)
        self.RoLb.setObjectName("RoLb")
        self.AxisHz.addWidget(self.RoLb)
        self.RoCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoCombo.sizePolicy().hasHeightForWidth())
        self.RoCombo.setSizePolicy(sizePolicy)
        self.RoCombo.setObjectName("RoCombo")
        self.RoCombo.addItem("")
        self.RoCombo.addItem("")
        self.RoCombo.addItem("")
        self.AxisHz.addWidget(self.RoCombo)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.AxisHz.addWidget(self.label_2)
        self.moveAx_cb = QtWidgets.QComboBox(self.centralwidget)
        self.moveAx_cb.setObjectName("moveAx_cb")
        self.moveAx_cb.addItem("")
        self.moveAx_cb.addItem("")
        self.moveAx_cb.addItem("")
        self.AxisHz.addWidget(self.moveAx_cb)
        self.SizeLb = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeLb.sizePolicy().hasHeightForWidth())
        self.SizeLb.setSizePolicy(sizePolicy)
        self.SizeLb.setObjectName("SizeLb")
        self.AxisHz.addWidget(self.SizeLb)
        self.SizeSp = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.SizeSp.setMaximum(9999.0)
        self.SizeSp.setSingleStep(0.01)
        self.SizeSp.setProperty("value", 1.0)
        self.SizeSp.setObjectName("SizeSp")
        self.AxisHz.addWidget(self.SizeSp)
        self.jntChain_rb = QtWidgets.QRadioButton(self.centralwidget)
        self.jntChain_rb.setObjectName("jntChain_rb")
        self.AxisHz.addWidget(self.jntChain_rb)
        self.verticalLayout.addLayout(self.AxisHz)
        self.InfoVz = QtWidgets.QVBoxLayout()
        self.InfoVz.setObjectName("InfoVz")
        self.ExistHz = QtWidgets.QHBoxLayout()
        self.ExistHz.setObjectName("ExistHz")
        self.ExLb = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExLb.sizePolicy().hasHeightForWidth())
        self.ExLb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ExLb.setFont(font)
        self.ExLb.setStyleSheet("background-color: rgb(126, 126, 126);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.ExLb.setObjectName("ExLb")
        self.ExistHz.addWidget(self.ExLb)
        self.InfoVz.addLayout(self.ExistHz)
        self.NetView = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NetView.sizePolicy().hasHeightForWidth())
        self.NetView.setSizePolicy(sizePolicy)
        self.NetView.setMinimumSize(QtCore.QSize(0, 0))
        self.NetView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.NetView.setObjectName("NetView")
        self.InfoVz.addWidget(self.NetView)
        self.verticalLayout.addLayout(self.InfoVz)
        self.CreateHz = QtWidgets.QHBoxLayout()
        self.CreateHz.setObjectName("CreateHz")
        self.RefreshPb = QtWidgets.QPushButton(self.centralwidget)
        self.RefreshPb.setObjectName("RefreshPb")
        self.CreateHz.addWidget(self.RefreshPb)
        self.ApplyPb = QtWidgets.QPushButton(self.centralwidget)
        self.ApplyPb.setObjectName("ApplyPb")
        self.CreateHz.addWidget(self.ApplyPb)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setObjectName("addBtn")
        self.CreateHz.addWidget(self.addBtn)
        self.MirrorPb = QtWidgets.QPushButton(self.centralwidget)
        self.MirrorPb.setObjectName("MirrorPb")
        self.CreateHz.addWidget(self.MirrorPb)
        self.MirrorPb1 = QtWidgets.QPushButton(self.centralwidget)
        self.MirrorPb1.setObjectName("MirrorPb1")
        self.CreateHz.addWidget(self.MirrorPb1)
        self.verticalLayout.addLayout(self.CreateHz)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 30))
        self.menubar.setObjectName("menubar")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_All_Settings = QtWidgets.QAction(MainWindow)
        self.actionExport_All_Settings.setObjectName("actionExport_All_Settings")
        self.actionImport_Settings = QtWidgets.QAction(MainWindow)
        self.actionImport_Settings.setObjectName("actionImport_Settings")
        self.actionCreate_AdvSettings = QtWidgets.QAction(MainWindow)
        self.actionCreate_AdvSettings.setObjectName("actionCreate_AdvSettings")
        self.actionCreate_TimelineSettings = QtWidgets.QAction(MainWindow)
        self.actionCreate_TimelineSettings.setObjectName("actionCreate_TimelineSettings")
        self.menuTool.addAction(self.actionExport_All_Settings)
        self.menuTool.addAction(self.actionImport_Settings)
        self.menuTool.addAction(self.actionCreate_AdvSettings)
        self.menuTool.addAction(self.actionCreate_TimelineSettings)
        self.menubar.addAction(self.menuTool.menuAction())

        self.retranslateUi(MainWindow)
        self.RoCombo.setCurrentIndex(0)
        self.moveAx_cb.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadPb.setText(_translate("MainWindow", "Load Joint"))
        self.ParentPb.setText(_translate("MainWindow", "Parent Joint"))
        self.label.setText(_translate("MainWindow", "side"))
        self.side_cb.setItemText(0, _translate("MainWindow", "L"))
        self.side_cb.setItemText(1, _translate("MainWindow", "R"))
        self.side_cb.setItemText(2, _translate("MainWindow", "M"))
        self.RoLb.setText(_translate("MainWindow", "Aim Axis"))
        self.RoCombo.setCurrentText(_translate("MainWindow", "x"))
        self.RoCombo.setItemText(0, _translate("MainWindow", "x"))
        self.RoCombo.setItemText(1, _translate("MainWindow", "y"))
        self.RoCombo.setItemText(2, _translate("MainWindow", "z"))
        self.label_2.setText(_translate("MainWindow", "move Axis"))
        self.moveAx_cb.setItemText(0, _translate("MainWindow", "x"))
        self.moveAx_cb.setItemText(1, _translate("MainWindow", "y"))
        self.moveAx_cb.setItemText(2, _translate("MainWindow", "z"))
        self.SizeLb.setText(_translate("MainWindow", "Size"))
        self.jntChain_rb.setText(_translate("MainWindow", "isJointChain"))
        self.ExLb.setText(_translate("MainWindow", "Existing"))
        self.RefreshPb.setText(_translate("MainWindow", "Refresh"))
        self.ApplyPb.setText(_translate("MainWindow", "Create(4)"))
        self.addBtn.setText(_translate("MainWindow", "Add"))
        self.MirrorPb.setText(_translate("MainWindow", "Mirror(L=>R)"))
        self.MirrorPb1.setText(_translate("MainWindow", "Mirror(R=>L)"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.actionExport_All_Settings.setText(_translate("MainWindow", "Export All Settings"))
        self.actionImport_Settings.setText(_translate("MainWindow", "Import Settings"))
        self.actionCreate_AdvSettings.setText(_translate("MainWindow", "Create Adv Settings"))
        self.actionCreate_TimelineSettings.setText(_translate("MainWindow", "Create Timeline Settings"))

