# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from vendor.Qt import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(441, 634)
        MainWidget.setMinimumSize(QtCore.QSize(10, 5))
        MainWidget.setStyleSheet("font: 15px \"Consolas\";\n"
"color: white;\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MainWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NameHz = QtWidgets.QHBoxLayout()
        self.NameHz.setSpacing(6)
        self.NameHz.setObjectName("NameHz")
        self.NameLb = QtWidgets.QLabel(MainWidget)
        self.NameLb.setObjectName("NameLb")
        self.NameHz.addWidget(self.NameLb)
        self.NameLe = QtWidgets.QLineEdit(MainWidget)
        self.NameLe.setObjectName("NameLe")
        self.NameHz.addWidget(self.NameLe)
        self.verticalLayout_3.addLayout(self.NameHz)
        self.LoadHz = QtWidgets.QHBoxLayout()
        self.LoadHz.setObjectName("LoadHz")
        self.LoadPb = QtWidgets.QPushButton(MainWidget)
        self.LoadPb.setObjectName("LoadPb")
        self.LoadHz.addWidget(self.LoadPb)
        self.LoadLe = QtWidgets.QLineEdit(MainWidget)
        self.LoadLe.setReadOnly(True)
        self.LoadLe.setObjectName("LoadLe")
        self.LoadHz.addWidget(self.LoadLe)
        self.verticalLayout_3.addLayout(self.LoadHz)
        self.ParentHz = QtWidgets.QHBoxLayout()
        self.ParentHz.setObjectName("ParentHz")
        self.ParentPb = QtWidgets.QPushButton(MainWidget)
        self.ParentPb.setObjectName("ParentPb")
        self.ParentHz.addWidget(self.ParentPb)
        self.ParentLe = QtWidgets.QLineEdit(MainWidget)
        self.ParentLe.setReadOnly(True)
        self.ParentLe.setObjectName("ParentLe")
        self.ParentHz.addWidget(self.ParentLe)
        self.verticalLayout_3.addLayout(self.ParentHz)
        self.AxisHz = QtWidgets.QHBoxLayout()
        self.AxisHz.setObjectName("AxisHz")
        self.RoLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoLb.sizePolicy().hasHeightForWidth())
        self.RoLb.setSizePolicy(sizePolicy)
        self.RoLb.setObjectName("RoLb")
        self.AxisHz.addWidget(self.RoLb)
        self.RoCombo = QtWidgets.QComboBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RoCombo.sizePolicy().hasHeightForWidth())
        self.RoCombo.setSizePolicy(sizePolicy)
        self.RoCombo.setObjectName("RoCombo")
        self.RoCombo.addItem("")
        self.RoCombo.addItem("")
        self.RoCombo.addItem("")
        self.AxisHz.addWidget(self.RoCombo)
        self.TrLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TrLb.sizePolicy().hasHeightForWidth())
        self.TrLb.setSizePolicy(sizePolicy)
        self.TrLb.setObjectName("TrLb")
        self.AxisHz.addWidget(self.TrLb)
        self.TrCombo = QtWidgets.QComboBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TrCombo.sizePolicy().hasHeightForWidth())
        self.TrCombo.setSizePolicy(sizePolicy)
        self.TrCombo.setObjectName("TrCombo")
        self.TrCombo.addItem("")
        self.TrCombo.addItem("")
        self.TrCombo.addItem("")
        self.AxisHz.addWidget(self.TrCombo)
        self.neg_cb = QtWidgets.QCheckBox(MainWidget)
        self.neg_cb.setObjectName("neg_cb")
        self.AxisHz.addWidget(self.neg_cb)
        self.verticalLayout_3.addLayout(self.AxisHz)
        self.InfoVz = QtWidgets.QVBoxLayout()
        self.InfoVz.setObjectName("InfoVz")
        self.ExistHz = QtWidgets.QHBoxLayout()
        self.ExistHz.setObjectName("ExistHz")
        self.ExLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExLb.sizePolicy().hasHeightForWidth())
        self.ExLb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ExLb.setFont(font)
        self.ExLb.setStyleSheet("background-color: rgb(126, 126, 126);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.ExLb.setObjectName("ExLb")
        self.ExistHz.addWidget(self.ExLb)
        self.InfoVz.addLayout(self.ExistHz)
        self.NetList = QtWidgets.QListWidget(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NetList.sizePolicy().hasHeightForWidth())
        self.NetList.setSizePolicy(sizePolicy)
        self.NetList.setMinimumSize(QtCore.QSize(0, 0))
        self.NetList.setObjectName("NetList")
        self.InfoVz.addWidget(self.NetList)
        self.EditVz = QtWidgets.QVBoxLayout()
        self.EditVz.setObjectName("EditVz")
        self.EditLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditLb.sizePolicy().hasHeightForWidth())
        self.EditLb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.EditLb.setFont(font)
        self.EditLb.setStyleSheet("background-color: rgb(126, 126, 126);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.EditLb.setObjectName("EditLb")
        self.EditVz.addWidget(self.EditLb)
        self.AxisHz_2 = QtWidgets.QHBoxLayout()
        self.AxisHz_2.setObjectName("AxisHz_2")
        self.OrderLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrderLb.sizePolicy().hasHeightForWidth())
        self.OrderLb.setSizePolicy(sizePolicy)
        self.OrderLb.setObjectName("OrderLb")
        self.AxisHz_2.addWidget(self.OrderLb)
        self.OrderCombo = QtWidgets.QComboBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrderCombo.sizePolicy().hasHeightForWidth())
        self.OrderCombo.setSizePolicy(sizePolicy)
        self.OrderCombo.setObjectName("OrderCombo")
        self.OrderCombo.addItem("")
        self.OrderCombo.addItem("")
        self.OrderCombo.addItem("")
        self.OrderCombo.addItem("")
        self.OrderCombo.addItem("")
        self.OrderCombo.addItem("")
        self.AxisHz_2.addWidget(self.OrderCombo)
        self.SizeLb = QtWidgets.QLabel(MainWidget)
        self.SizeLb.setObjectName("SizeLb")
        self.AxisHz_2.addWidget(self.SizeLb)
        self.SizeSp = QtWidgets.QDoubleSpinBox(MainWidget)
        self.SizeSp.setFrame(False)
        self.SizeSp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SizeSp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.SizeSp.setKeyboardTracking(True)
        self.SizeSp.setMinimum(1.0)
        self.SizeSp.setMaximum(99999999.0)
        self.SizeSp.setSingleStep(0.01)
        self.SizeSp.setObjectName("SizeSp")
        self.AxisHz_2.addWidget(self.SizeSp)
        self.EditVz.addLayout(self.AxisHz_2)
        self.InterHz = QtWidgets.QHBoxLayout()
        self.InterHz.setObjectName("InterHz")
        self.InterLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterLb.sizePolicy().hasHeightForWidth())
        self.InterLb.setSizePolicy(sizePolicy)
        self.InterLb.setObjectName("InterLb")
        self.InterHz.addWidget(self.InterLb)
        self.InterTypeCombo = QtWidgets.QComboBox(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InterTypeCombo.sizePolicy().hasHeightForWidth())
        self.InterTypeCombo.setSizePolicy(sizePolicy)
        self.InterTypeCombo.setObjectName("InterTypeCombo")
        self.InterTypeCombo.addItem("")
        self.InterTypeCombo.addItem("")
        self.InterTypeCombo.addItem("")
        self.InterHz.addWidget(self.InterTypeCombo)
        self.EditVz.addLayout(self.InterHz)
        self.RangeGz = QtWidgets.QGridLayout()
        self.RangeGz.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.RangeGz.setSpacing(6)
        self.RangeGz.setObjectName("RangeGz")
        self.EndLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndLb.sizePolicy().hasHeightForWidth())
        self.EndLb.setSizePolicy(sizePolicy)
        self.EndLb.setObjectName("EndLb")
        self.RangeGz.addWidget(self.EndLb, 1, 2, 1, 1)
        self.StartLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartLb.sizePolicy().hasHeightForWidth())
        self.StartLb.setSizePolicy(sizePolicy)
        self.StartLb.setObjectName("StartLb")
        self.RangeGz.addWidget(self.StartLb, 1, 1, 1, 1)
        self.InputLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputLb.sizePolicy().hasHeightForWidth())
        self.InputLb.setSizePolicy(sizePolicy)
        self.InputLb.setObjectName("InputLb")
        self.RangeGz.addWidget(self.InputLb, 2, 0, 1, 1)
        self.OutputLb = QtWidgets.QLabel(MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputLb.sizePolicy().hasHeightForWidth())
        self.OutputLb.setSizePolicy(sizePolicy)
        self.OutputLb.setObjectName("OutputLb")
        self.RangeGz.addWidget(self.OutputLb, 3, 0, 1, 1)
        self.InStSp = QtWidgets.QDoubleSpinBox(MainWidget)
        self.InStSp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.InStSp.setDecimals(1)
        self.InStSp.setMinimum(-999.0)
        self.InStSp.setMaximum(999.0)
        self.InStSp.setSingleStep(0.1)
        self.InStSp.setObjectName("InStSp")
        self.RangeGz.addWidget(self.InStSp, 2, 1, 1, 1)
        self.InEdSp = QtWidgets.QDoubleSpinBox(MainWidget)
        self.InEdSp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.InEdSp.setDecimals(1)
        self.InEdSp.setMinimum(-999.0)
        self.InEdSp.setMaximum(999.0)
        self.InEdSp.setSingleStep(0.1)
        self.InEdSp.setProperty("value", 90.0)
        self.InEdSp.setObjectName("InEdSp")
        self.RangeGz.addWidget(self.InEdSp, 2, 2, 1, 1)
        self.OutStSp = QtWidgets.QDoubleSpinBox(MainWidget)
        self.OutStSp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.OutStSp.setDecimals(1)
        self.OutStSp.setMaximum(999.0)
        self.OutStSp.setSingleStep(0.1)
        self.OutStSp.setObjectName("OutStSp")
        self.RangeGz.addWidget(self.OutStSp, 3, 1, 1, 1)
        self.OutEdSp = QtWidgets.QDoubleSpinBox(MainWidget)
        self.OutEdSp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.OutEdSp.setDecimals(1)
        self.OutEdSp.setMaximum(999.0)
        self.OutEdSp.setSingleStep(0.1)
        self.OutEdSp.setProperty("value", 1.0)
        self.OutEdSp.setObjectName("OutEdSp")
        self.RangeGz.addWidget(self.OutEdSp, 3, 2, 1, 1)
        self.EditVz.addLayout(self.RangeGz)
        self.InfoVz.addLayout(self.EditVz)
        self.verticalLayout_3.addLayout(self.InfoVz)
        self.CreateHz = QtWidgets.QHBoxLayout()
        self.CreateHz.setObjectName("CreateHz")
        self.RefreshPb = QtWidgets.QPushButton(MainWidget)
        self.RefreshPb.setObjectName("RefreshPb")
        self.CreateHz.addWidget(self.RefreshPb)
        self.ApplyPb = QtWidgets.QPushButton(MainWidget)
        self.ApplyPb.setObjectName("ApplyPb")
        self.CreateHz.addWidget(self.ApplyPb)
        self.MirrorPb = QtWidgets.QPushButton(MainWidget)
        self.MirrorPb.setObjectName("MirrorPb")
        self.CreateHz.addWidget(self.MirrorPb)
        self.verticalLayout_3.addLayout(self.CreateHz)

        self.retranslateUi(MainWidget)
        self.RoCombo.setCurrentIndex(1)
        self.TrCombo.setCurrentIndex(2)
        self.OrderCombo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "Form"))
        self.NameLb.setText(_translate("MainWidget", "Name"))
        self.LoadPb.setText(_translate("MainWidget", "Load Joint"))
        self.ParentPb.setText(_translate("MainWidget", "Parent Joint"))
        self.RoLb.setText(_translate("MainWidget", "Rotate"))
        self.RoCombo.setCurrentText(_translate("MainWidget", "Y"))
        self.RoCombo.setItemText(0, _translate("MainWidget", "X"))
        self.RoCombo.setItemText(1, _translate("MainWidget", "Y"))
        self.RoCombo.setItemText(2, _translate("MainWidget", "Z"))
        self.TrLb.setText(_translate("MainWidget", "Translate"))
        self.TrCombo.setCurrentText(_translate("MainWidget", "Z"))
        self.TrCombo.setItemText(0, _translate("MainWidget", "X"))
        self.TrCombo.setItemText(1, _translate("MainWidget", "Y"))
        self.TrCombo.setItemText(2, _translate("MainWidget", "Z"))
        self.neg_cb.setText(_translate("MainWidget", "negtive"))
        self.ExLb.setText(_translate("MainWidget", "Existing"))
        self.EditLb.setText(_translate("MainWidget", "Edit"))
        self.OrderLb.setText(_translate("MainWidget", "Rotate Order"))
        self.OrderCombo.setCurrentText(_translate("MainWidget", "YZX"))
        self.OrderCombo.setItemText(0, _translate("MainWidget", "XYZ"))
        self.OrderCombo.setItemText(1, _translate("MainWidget", "YZX"))
        self.OrderCombo.setItemText(2, _translate("MainWidget", "ZXY"))
        self.OrderCombo.setItemText(3, _translate("MainWidget", "XZY"))
        self.OrderCombo.setItemText(4, _translate("MainWidget", "YXZ"))
        self.OrderCombo.setItemText(5, _translate("MainWidget", "ZYX"))
        self.SizeLb.setText(_translate("MainWidget", "Size"))
        self.InterLb.setText(_translate("MainWidget", "Interpolation"))
        self.InterTypeCombo.setItemText(0, _translate("MainWidget", "Linear"))
        self.InterTypeCombo.setItemText(1, _translate("MainWidget", "Smooth"))
        self.InterTypeCombo.setItemText(2, _translate("MainWidget", "Spline"))
        self.EndLb.setText(_translate("MainWidget", "End"))
        self.StartLb.setText(_translate("MainWidget", "Start"))
        self.InputLb.setText(_translate("MainWidget", "Input"))
        self.OutputLb.setText(_translate("MainWidget", "Output"))
        self.RefreshPb.setText(_translate("MainWidget", "Refresh"))
        self.ApplyPb.setText(_translate("MainWidget", "Create"))
        self.MirrorPb.setText(_translate("MainWidget", "Mirror"))


